copy data\newdata\SUBCY.csv winners\.
copy data\newdata\PPTA.csv winners\.
copy data\newdata\CNQ.csv winners\.
copy data\newdata\LEU.csv winners\.
copy data\newdata\TECK.csv winners\.
copy data\newdata\MDGL.csv winners\.
copy data\newdata\TAYD.csv winners\.
copy data\newdata\HROW.csv winners\.
copy data\newdata\EDVMF.csv winners\.
copy data\newdata\TORXF.csv winners\.
copy data\newdata\ALNT.csv winners\.
copy data\newdata\TER.csv winners\.
copy data\newdata\KTOS.csv winners\.
copy data\newdata\CYD.csv winners\.
copy data\newdata\CAMT.csv winners\.
copy data\newdata\AIR.csv winners\.
copy data\newdata\TPR.csv winners\.
copy data\newdata\WDC.csv winners\.
copy data\newdata\STX.csv winners\.
copy data\newdata\AGI.csv winners\.
copy data\newdata\CELH.csv winners\.
copy data\newdata\PATK.csv winners\.
copy data\newdata\OCANF.csv winners\.
copy data\newdata\AEHR.csv winners\.
copy data\newdata\TBBK.csv winners\.
copy data\newdata\TOELY.csv winners\.
copy data\newdata\ATEYY.csv winners\.
copy data\newdata\BBW.csv winners\.
copy data\newdata\PSIX.csv winners\.
copy data\newdata\CFG.csv winners\.
copy data\newdata\LSCC.csv winners\.
copy data\newdata\FTAI.csv winners\.
copy data\newdata\BVN.csv winners\.
copy data\newdata\AX.csv winners\.
copy data\newdata\AVAV.csv winners\.
copy data\newdata\SIMO.csv winners\.
copy data\newdata\LUGDF.csv winners\.
copy data\newdata\SNEX.csv winners\.
copy data\newdata\TCI.csv winners\.
copy data\newdata\FCX.csv winners\.
copy data\newdata\BELFB.csv winners\.
copy data\newdata\STLD.csv winners\.
copy data\newdata\ENVA.csv winners\.
copy data\newdata\CCJ.csv winners\.
copy data\newdata\CRZBY.csv winners\.
copy data\newdata\FEIM.csv winners\.
copy data\newdata\NIC.csv winners\.
copy data\newdata\ONTO.csv winners\.
copy data\newdata\ESLT.csv winners\.
copy data\newdata\AXSM.csv winners\.
copy data\CMCL.csv winners\.
copy data\APH.csv winners\.
copy data\LITE.csv winners\.
copy data\IMVT.csv winners\.
copy data\IIIN.csv winners\.
copy data\EAT.csv winners\.
copy data\NVMI.csv winners\.
copy data\PLPC.csv winners\.
copy data\PNRG.csv winners\.
copy data\GRAL.csv winners\.
copy data\BLBD.csv winners\.
copy data\ZM.csv winners\.
copy data\TPC.csv winners\.
copy data\AEO.csv winners\.
copy data\ESOA.csv winners\.
copy data\BYD.csv winners\.
copy data\FBP.csv winners\.
copy data\FUNC.csv winners\.
copy data\FRBA.csv winners\.
copy data\PDEX.csv winners\.
copy data\NUE.csv winners\.
copy data\TGLS.csv winners\.
copy data\F.csv winners\.
copy data\ACU.csv winners\.
copy data\ATEN.csv winners\.
copy data\GTX.csv winners\.
copy data\FIX.csv winners\.
copy data\CWK.csv winners\.
copy data\RCMT.csv winners\.
copy data\RCL.csv winners\.
copy data\HMY.csv winners\.
copy data\AEIS.csv winners\.
copy data\MATX.csv winners\.
copy data\NGD.csv winners\.
copy data\CLS.csv winners\.
copy data\B.csv winners\.
copy data\INOD.csv winners\.
copy data\RMBS.csv winners\.
copy data\FOXA.csv winners\.
copy data\GM.csv winners\.
copy data\UNM.csv winners\.
copy data\MYRG.csv winners\.
copy data\PAG.csv winners\.
copy data\AEM.csv winners\.
copy data\LRCX.csv winners\.
copy data\SPRY.csv winners\.
copy data\FN.csv winners\.
copy data\LMB.csv winners\.
copy data\SMID.csv winners\.
copy data\CBRE.csv winners\.
copy data\WTFC.csv winners\.
copy data\MTZ.csv winners\.
copy data\RBCAA.csv winners\.
copy data\KLAC.csv winners\.
copy data\FLEX.csv winners\.
copy data\HBM.csv winners\.
copy data\NG.csv winners\.
copy data\LMAT.csv winners\.
copy data\XPEL.csv winners\.
copy data\DOCN.csv winners\.
copy data\CASH.csv winners\.
copy data\SANM.csv winners\.
copy data\ATLC.csv winners\.
copy data\MC.csv winners\.
copy data\EVR.csv winners\.
copy data\CWCO.csv winners\.
copy data\PNFP.csv winners\.
copy data\DXC.csv winners\.
copy data\NEM.csv winners\.
copy data\LINC.csv winners\.
copy data\NXT.csv winners\.
copy data\NFLX.csv winners\.
copy data\LLY.csv winners\.
copy data\PLXS.csv winners\.
copy data\PIPR.csv winners\.
copy data\LMND.csv winners\.
copy data\DGII.csv winners\.
copy data\HCI.csv winners\.
copy data\ZWS.csv winners\.
copy data\IESC.csv winners\.
copy data\CRS.csv winners\.
copy data\AMKR.csv winners\.
copy data\MTSI.csv winners\.
copy data\GHM.csv winners\.
copy data\FTNT.csv winners\.
copy data\NGVC.csv winners\.
copy data\KINS.csv winners\.
copy data\AU.csv winners\.
copy data\TGB.csv winners\.
copy data\GFI.csv winners\.
copy data\KGC.csv winners\.
