@echo off
rem Year-High (YH) backtest — outputs YH_Closed|Open|Scanner|Watchlist_<ts>.csv in drive\
rem Standalone: double-click or call from DailyRun. Override: set YH_SYMBOLS=SYM1,SYM2 before calling.
rem IND_TC_* on Closed: change use_indicators=false → true below (report-only; indicator_buy=off = no gates).
setlocal EnableExtensions
cd /d "%~dp0"
if not defined PY call "%~dp0resolve_python.bat"
if errorlevel 1 exit /b 1

if not defined YH_SYMBOLS set "YH_SYMBOLS=AAL,AAMI,AAON,AAPL,ABBNY,ABBV,ABCB,ABG,ABT,ACA,ACGL,ACLS,ACN,ADBE,ADP,AEIS,AEP,AFL,AGI,AGM,AGO,AGYS,AIR,AIZ,AJG,ALFVY,ALG,ALGN,ALL,ALNT,ALNY,ALSN,AMAT,AMD,AME,AMGN,AMKR,AMN,AMP,AMRC,AMZN,AN,ANET,ANF,ANIK,AON,AOS,APG,APH,APP,ARES,ARGX,ARW,ASH,ASMIY,ASML,ATEYY,ATO,AU,AVAV,AVGO,AVY,AWK,AX,AXON,AXP,AXSM,AYI,AZO,BA,BAC,BAESY,BANF,BDX,BELFA,BELFB,BEP,BIO,BKNG,BLBD,BLK,BLX,BN,BPOP,BR,BRO,BSX,BVN,BWXT,BX,BYD,CACI,CAMT,CARR,CASH,CASY,CAT,CB,CBOE,CBRE,CCEP,CDNS,CF,CHD,CHDN,CHKP,CHTR,CIEN,CINF,CLS,CME,CMI,CMS,CNC,CNO,COKE,COO,CORT,COST,CPRT,CRH,CRL,CRM,CRWD,CSCO,CSGP,CSL,CSX,CTAS,CTS,CVCO,CW,DAL,DBSDY,DCO,DDS,DE,DG,DGX,DHI,DHR,DKS,DOV,DPZ,DRI,DSGX,DTE,DXCM,DY,EA,EBAY,EBKDY,ECL,EFX,EGP,EHC,EL,ELV,EME,ENPH,ENS,ENSG,ENVA,EPAM,ESE,ESLT,ESOA,ETR,EXEL,EXLS,EXPE,EXR,FAST,FDS,FICO,FINMY,FIS,FISV,FIX,FLEX,FN,FNF,FNV,FTAI,FTNT,FUNC,GD,GDDY,GE,GL,GLW,GMAB,GNRC,GOOG,GOOGL,GPN,GRMN,GS,GVA,HALO,HCI,HD,HIG,HLI,HLT,HON,HRL,HROW,HUBB,HWBK,HWM,IBKR,IBP,ICE,IDA,IDXX,IESC,IEX,ING,INTU,IQV,IRM,IRMD,ISRG,IT,ITIC,ITRN,ITT,ITW,J,JBHT,JBL,JCI,JKHY,JNJ,JOE,JPM,KDP,KEYS,KGC,KLAC,KR,KTOS,LAD,LDOS,LHX,LII,LIN,LINC,LLY,LMAT,LMT,LNT,LOGI,LOPE,LOW,LPG,LRCX,LSCC,LUGDF,LULU,LUV,LYV,MA,MAR,MAS,MATX,MCD,MCK,MCO,MCRI,MDU,MELI,META,MITSY,MKC,MLI,MNST,MO,MORN,MPC,MPWR,MRK,MRVL,MS,MSCI,MSFT,MSI,MTD,MTSI,MU,MWA,MYRG,NBHC,NBIX,NDAQ,NDSN,NEE,NEO,NFLX,NHC,NIC,NKE,NMIH,NNI,NOC,NOW,NPO,NSC,NTAP,NTRA,NTRS,NVAX,NVDA,NVMI,NVR,NWPX,NXPI,NXST,NYT,OC,ODC,ODFL,OLED,OMAB,ON,ONTO,OPY,ORCL,ORI,ORLY,OVCHY,PAG,PANW,PATK,PAYC,PAYX,PCVX,PDEX,PEG,PFG,PFSI,PG,PGR,PH,PIPR,PKG,PLD,PLPC,PLTR,PLUS,PLXS,PNFP,PNR,POOL,POWL,PRI,PSA,PTC,PWR,PYPL,QCOM,R,RBA,RBC,RBCAA,RCL,RDNT,RELX,RF,RGC,RJF,RMBS,RMD,RNG,RNMBY,ROK,ROP,ROST,RSG,RTX,RUSHB,RVTY,RY,SAFRY,SAIA,SANM,SBAC,SCHW,SHW,SIMO,SJM,SKYW,SMID,SMTOY,SNA,SNEX,SNPS,SNX,SO,SONY,SPRY,SPXC,SPXCY,SRPT,STE,STLD,STRL,SUPN,SVM,SWK,SWKS,SYK,SYY,TATT,TBBK,TDG,TDY,TECH,TER,TFC,TFX,TGB,TGLS,THG,TJX,TKO,TMO,TMUS,TOELY,TPR,TRV,TSEM,TSLA,TSM,TSN,TT,TTWO,TYL,UAL,ULTA,UNH,UNM,UNP,URI,UTHR,UTI,V,VLO,VMC,VRSK,VRSN,VRTX,VSEC,WAB,WAT,WCC,WINA,WM,WMB,WMT,WOR,WRB,WRLD,WST,WTS,WWD,XEL,XPO,YUM,ZBRA,ZIJMY,ZTS,ZWS"

"%PY%" stock_analysis\rocket_brt.py data\newdata\data -o drive -w 32 --aggressive --use-duckdb --no-regression -v yh_zones=true -v brt_zones=false -v wpbr_zones=false -v rl_mode=false -v band_pct=0.0099 -v yh_move_away_pct=0.031 -v yh_lookback=252 -v yh_memory_mode=sheet -v strong_pre_pivot_bars=7 -v strong_pre_pivot_pct=0.12 -v strong_post_pivot_bars=7 -v strong_post_pivot_pct=0.109 -v strong_pivot_mode=both -v target_pct=1.27 -v stop_pct=0.923 -v stop_pct_is_multiplier=true -v too_high_multiplier=0 -v min_spy_compare_1y_at_trigger=97.5 -v max_spy_compare_1y_at_trigger=0 -v min_atr_pct_at_trigger=0 -v max_atr_pct_at_trigger=0 -v growth_filter_enabled=true -v growth_bars=756 -v use_indicators=false -v indicator_buy=off -v ind_score_weights_path=stock_analysis\ind_score_weights_260609152353.json -v min_ind_score=0 -v indicator_diff=10 -v symbol_reentry_cooldown_days=20 -v too_high_multiplier=1.04 -s "%YH_SYMBOLS%"
exit /b %errorlevel%

