rem python stock_analysis/rocket_brt.py data/newdata/data -o drive -w 5 --aggressive -v target_pct=1.21 -v atr_target=0 -v atr_stop=0 -v trailing_stop_increment=0 -v strong_pre_pivot_pct=0.081 -v strong_post_pivot_pct=0.108 -v atr_progress=0 -v atr_days=0 -v band_pct_atr=0 -v relative_strength_enabled=false -v compute_beta=true -v min_avg_volume_10d_at_entry=0 -v min_atr_pct_at_entry=0 -v max_market_cap=111111164166115120 -v post_entry_gain_pct=20 -v post_entry_gain_calendar_days=75 -v sheet_dw_countif_include_prior_bar_date=false --print-zones -s "AAPL,ABBV,ACN,ADBE,ADI,AMAT,AMD,AMZN,AU,AVGO,AXP,BABA,BAC,CDNS,CI,CRM,CRWD,DIS,GILD,GOOG,GOOGL,HD,JPM,KO,KR,LOW,LYV,META,MPC,MS,MSFT,MU,NEM,NFLX,NVDA,ORCL,PFE,PG,PLTR,PM,PPTA,SHOP,TMUS,TSLA,TSM,UNH,V,WFC,WMT,XOM" 

rem python gettarget.py --brt-atr-target=0 --brt-atr-stop=0 --brt-atr-increment=0 --brt-atr-progress=0 --brt-atr-days=0 --ind-atr-target=2.2 --ind-atr-stop=0.6 --ind-atr-increment=0 --ind-atr-progress=0.9 --ind-atr-days=6 --rl-target-pct=1.20 --rl-stop-pct=0.934 --rl-use-sma50 --rl-trail-profit=0.14 --rl-trail-stop=0 --rl-trail-profit2=0.40 --rl-trail-stop2=0.20

REM MTS

python stock_analysis\rocket_brt.py data\newdata\data -o drive -w 5 --aggressive --no-regression --mts-sheet-parity -v band_pct=0.018 -v touch_threshold=2 -v strong_post_pivot_bars=8 -v strong_post_pivot_pct=0.06 -v strong_pre_pivot_bars=6 -v strong_pre_pivot_pct=0.12 -v target_pct=1.22 -v stop_pct=0.934 -v stop_pct_is_multiplier=true -v stop_anchor=signal_low -v aggressive_avg_positions=18 -s "AAON,ABCB,ABG,ACA,ACU,ALG,AMD,AMN,APP,ARES,ATEYY,AU,BBW,BELFA,BWLP,CHCI,CIEN,CLS,CMC,COHR,COKE,CRS,CRWD,CSTM,CVCO,DDS,DECK,DKL,DKS,DXCM,DY,ENVA,ESP,EVR,FEIM,FN,FRD,FTAI,HWKN,IBP,IESC,IR,JOE,LMAT,LOGI,LRCX,LUGDF,LULU,MATX,MOD,MPWR,MTSI,MTZ,MYRG,NEO,NGL,NVDA,NVMI,NXPI,OR,PFSI,PLUS,POOL,POWL,PTC,QXO,RMBS,SANM,SCCO,SGI,SHOP,SIMO,SKYW,TATT,TBBK,TER,TOELY,TPH,TRT,TWLO,UHS,URI,UTI,VSEC,WDAY,WOR,XPO"

REM BRT
REM python stock_analysis\rocket_brt.py data\newdata\data -o drive -w 5 --aggressive --no-regression -v compute_beta=true -v min_atr_pct_at_entry=2 -v max_market_cap=111111164166115120 -v post_entry_gain_pct=20 -v post_entry_gain_calendar_days=75 -v sheet_dw_countif_include_prior_bar_date=false --print-zones -v atr_progress_incremental_stop=false -v stop_pct=0.903 -v too_high_multiplier=1.058 -v band_pct=0.017 -v short_target_pct=1.18 -v transaction_type=long -v entry_type=long -v growth_filter_enabled=true -v short_stop_pct=0.95 -v min_ind_score=-1 -s "AAPL,ABBV,ACN,ADBE,ADI,AMAT,AMD,AMZN,AU,AVGO,AXP,BABA,BAC,CDNS,CI,CRM,CRWD,DIS,GILD,GOOG,GOOGL,HD,JPM,KO,KR,LOW,LYV,META,MPC,MS,MSFT,MU,NEM,NFLX,NVDA,ORCL,PFE,PG,PLTR,PM,PPTA,SHOP,TMUS,TSLA,TSM,UNH,V,WFC,WMT,XOM"

rem powershell .\run_audit.ps1 -s "TSLA,AMD,INTC,XOM,LRCX,NFLX,PLTR,KLAC,WFC,ADI,STX,WDC,ANET,APP,TOELY,IBKR,CRWD,ATEYY,NEM,AEM,CNQ,FCX,FTNT,MPWR,MELI,B,FIX,RCL,GM,TER,OKE,OXY,AU,TRGP,DVN,FLEX,CCJ,ARGX,F,CLS,IDXX,EME,GFI,ARES,KGC,ESLT,STLD,MTZ,TECK,WDAY,TWLO,NRG,RMD,FOXA,FTAI,NTRA,FTI,MTSI,TPR,STRL,CFG,FOX,FSLR,ALB,FN,KEY,AKAM,TEAM,BEP,LEN,CRS,RL,DKS,AMKR,NXT"

rem python stock_analysis\BRT_DrawdownCalc.py Drive\IND_Closed_260602180527.csv 

REM LONG YH

REM python stock_analysis\rocket_brt.py data\newdata\data -o drive -w 5 --aggressive --use-duckdb --no-regression -v yh_zones=true -v brt_zones=false -v band_pct=0.015 -v strong_pre_pivot_pct=0.12 -v strong_post_pivot_pct=0.109 -v min_spy_compare_1y_at_trigger=-1000 -v ind_score_weights_path="" -v too_high_multiplier=0 -v yh_move_away_pct=0.036 -v target_pct=1.26 -v stop_pct=0.86 -v yh_memory_mode=parallel -s "NVDA, MSFT, AAPL, AMZN, META, NFLX, AMD, AU, GOOGL,TSLA"

REM python stock_analysis\rocket_brt.py data\newdata\data -o drive -w 6 --aggressive --use-duckdb --no-regression -v yh_zones=true -v brt_zones=false -v band_pct=0.015 -v strong_pre_pivot_pct=0.12 -v strong_post_pivot_pct=0.109 -v min_spy_compare_1y_at_trigger=-1000 -v ind_score_weights_path="" -v too_high_multiplier=0 -v yh_move_away_pct=0.03 -v target_pct=1.25 -v stop_pct=0.928 -v atr_target=2.3 -v atr_stop=2.5 -s "AAPL, MSFT, GOOGL, AMZN, NVDA, META, TSLA, NFLX"

REM LONG IND

REM python stock_analysis\rocket_brt.py data\newdata\data -o drive -w 5 --aggressive --use-duckdb --no-regression -v target_pct=1.21 -v trailing_stop_increment=0 -v strong_pre_pivot_pct=0.081 -v strong_post_pivot_pct=0.109 -v atr_progress=0 -v atr_days=0 -v compute_beta=true -v min_avg_volume_10d_at_entry=0 -v min_atr_pct_at_trigger=8.1 -v max_atr_pct_at_trigger=0 -v use_indicators=true -v indicator_buy=only -v indicator_diff=11 -v indicator_sides=long -v transaction_type=long -v atr_target=2.4 -v atr_stop=1.1 -v max_ind_entry_neutral_n=29 -v yh_zones=false 

REM stock_analysis/rocket_brt.py data/newdata/data -o drive -w 5 --aggressive --no-regression --aggressive-sizing-equity-cap=999 -v aggressive_avg_positions=6 --use-duckdb -v target_pct=1.21 -v atr_progress=0 -v atr_days=0  -v compute_beta=false -v use_indicators=true -v indicator_buy=only -v indicator_sides=long -v transaction_type=long -v  atr_target=0 -v atr_stop=0 -v sell_ind_diff_below=0 -v exit_ind_diff_only=false -v use_ind_score=true -v use_sma50=false -v sma_stop_days=0 -v post_entry_gain_pct=10 -v post_entry_gain_calendar_days=30 -v growth_filter_enabled=false -v require_close_gt_open=false -v ind_score_weights_path=ind_score_weights_260608190347.json -v too_high_multiplier=0 -v entry_close_min_range_position=0 -v too_low_multiplier=0 -v symbol_reentry_cooldown_days=0 -v margin_utilization=1 -v max_touch_count_short=0 -v entry_filter_meteoric_rise=both -v entry_filter_meteoric_fall=both -v min_atr_pct_at_trigger=0 -v indicator_diff=-100 -v max_ind_entry_neutral_n=1000 -v min_ind_score=0 -v sell_on_low_vol=0.1 -v min_dist_to_52w_high_pct_at_trigger=0 -v min_spy_compare_1y_at_trigger=0 -v stop_pct=0.96 -v mandatory_ind_states_path=mandatory_ind_states.json

REM SHORT
rem python stock_analysis/rocket_brt.py data/newdata/data -o drive -w 5 --aggressive --profile --use-duckdb -v target_pct=1.21 -v trailing_stop_increment=0 -v strong_pre_pivot_pct=0.081 -v strong_post_pivot_pct=0.109 -v atr_progress=0 -v atr_days=0  -v compute_beta=true -v min_avg_volume_10d_at_entry=0 -v min_atr_pct_at_entry=7.2 -v max_atr_pct_at_entry=0 -v use_indicators=true -v indicator_buy=only -v indicator_diff=10 -v indicator_sides=short -v transaction_type=short -v short_target=1.2


REM python stock_analysis/rocket_brt.py data/newdata/data -o drive -w 5 --aggressive --profile --use-duckdb -v target_pct=1.21 -v trailing_stop_increment=0 -v strong_pre_pivot_pct=0.081 -v strong_post_pivot_pct=0.109 -v atr_progress=0 -v atr_days=0  -v compute_beta=true -v min_avg_volume_10d_at_entry=0 -v min_atr_pct_at_entry=7.2 -v max_atr_pct_at_entry=0 -v use_indicators=true -v indicator_buy=only -v indicator_diff=10 -s "NVDA,WDC,SHOP,NEM,CIEN,LITE,NET,B,REGN,OXY,FANG,AU,GFI,HUM,KGC,TECK,TWLO,NTRA,ZS,MDB,FN,FTAI,INSM,TEAM,WWD,EXAS,CDE,WES,DLTR,AGI,DOCN,OKTA,RGC,APA,SGI,UNM,BBIO,GH,BBY,APLD,MDGL,SANM,U,AXSM,VIRT


rem python stock_analysis/rocket_brt.py data/newdata/data -o drive -w 5 --aggressive -v target_pct=1.21 -v trailing_stop_increment=0 -v strong_pre_pivot_pct=0.081 -v strong_post_pivot_pct=0.109 -v atr_progress=0 -v atr_days=0  -v compute_beta=true -v min_avg_volume_10d_at_entry=0 -v min_atr_pct_at_entry=2 -v max_market_cap=111111164166115120 -v post_entry_gain_pct=20 -v post_entry_gain_calendar_days=75 -v sheet_dw_countif_include_prior_bar_date=false --print-zones  -v atr_progress_incremental_stop=false -v stop_pct=0.903 -v too_high_multiplier=1.058 -v band_pct=0.017 -v short_target_pct=1.18 -v transaction_type=long -v entry_type=long -v growth_filter_enabled=true -v short_stop_pct=0.95 -v use_indicators=true -v indicator_buy=only -s "AAPL,ABBV,ACN,ADBE,ADI,AMAT,AMD,AMZN,AU,AVGO,AXP,BABA,BAC,CDNS,CI,CRM,CRWD,DIS,GILD,GOOG,GOOGL,HD,JPM,KO,KR,LOW,LYV,META,MPC,MS,MSFT,MU,NEM,NFLX,NVDA,ORCL,PFE,PG,PLTR,PM,PPTA,SHOP,TMUS,TSLA,TSM,UNH,V,WFC,WMT,XOM" 

rem python stock_analysis/rocket_brt.py data/newdata/data -o drive -w 5 --aggressive -v target_pct=1.21 -v trailing_stop_increment=0 -v strong_pre_pivot_pct=0.081 -v strong_post_pivot_pct=0.109 -v atr_progress=0 -v atr_days=0  -v compute_beta=true -v min_avg_volume_10d_at_entry=0 -v min_atr_pct_at_entry=2 -v max_market_cap=111111164166115120 -v post_entry_gain_pct=20 -v post_entry_gain_calendar_days=75 -v sheet_dw_countif_include_prior_bar_date=false --print-zones  -v atr_progress_incremental_stop=false -v stop_pct=0.903 -v too_high_multiplier=1.058 -v band_pct=0.017 -v short_target_pct=1.18 -v transaction_type=long -v entry_type=long -v growth_filter_enabled=true -v short_stop_pct=0.95 -v use_indicators=true -v indicator_buy=only -v indicator_diff=10

