rem python stock_analysis/rocket_tbn.py data/newdata/data -o drive -w 16 --aggressive -v target_pct=1.21 -v atr_target=0 -v atr_stop=0 -v trailing_stop_increment=0 -v strong_pre_pivot_pct=0.081 -v strong_post_pivot_pct=0.108 -v atr_progress=0 -v atr_days=0 -v band_pct_atr=0 -v relative_strength_enabled=false -v compute_beta=true -v min_avg_volume_10d_at_entry=0 -v min_atr_pct_at_entry=0 -v max_market_cap=111111164166115120 -v post_entry_gain_pct=20 -v post_entry_gain_calendar_days=75 -v sheet_dw_countif_include_prior_bar_date=false --print-zones -s "AAPL,ABBV,ACN,ADBE,ADI,AMAT,AMD,AMZN,AU,AVGO,AXP,BABA,BAC,CDNS,CI,CRM,CRWD,DIS,GILD,GOOG,GOOGL,HD,JPM,KO,KR,LOW,LYV,META,MPC,MS,MSFT,MU,NEM,NFLX,NVDA,ORCL,PFE,PG,PLTR,PM,PPTA,SHOP,TMUS,TSLA,TSM,UNH,V,WFC,WMT,XOM" 

rem python gettarget.py --brt-atr-target=0 --brt-atr-stop=0 --brt-atr-increment=0 --brt-atr-progress=0 --brt-atr-days=0 --ind-atr-target=2.2 --ind-atr-stop=0.6 --ind-atr-increment=0 --ind-atr-progress=0.9 --ind-atr-days=6 --rl-target-pct=1.20 --rl-stop-pct=0.934 --rl-use-sma50 --rl-trail-profit=0.14 --rl-trail-stop=0 --rl-trail-profit2=0.40 --rl-trail-stop2=0.20

REM WPBR
REM python stock_analysis\rocket_tbn.py data\newdata\data -o drive -w 16 --aggressive --no-regression --print-zones -v wpbr_zones=true -v brt_zones=false -v yh_zones=false -v vec_zones=false -v band_pct=0.015 -v strong_pre_pivot_bars=5 -v strong_pre_pivot_pct=0.01 -v strong_post_pivot_bars=7 -v strong_post_pivot_pct=0.02 -v strong_pivot_mode=either -v wpbr_breakout_confirmation=0.01 -v wpbr_max_days_after_retest=2 -v growth_filter_enabled=true -v growth_bars=1200 -v min_spy_compare_1y_at_trigger=-1000 -v ind_score_weights_path="" -v too_high_multiplier=0 -v target_pct=1.22 -v stop_pct=0.91 

REM MarkTen -s "AMZN,AMD,AU,GOOGL,META,TSLA,NFLX,MSFT,AAPL,NVDA"
REM MTS

REM python stock_analysis\rocket_tbn.py data\newdata\data -o drive -w 16 --aggressive --no-regression --mts-sheet-parity -v band_pct=0.018 -v touch_threshold=2 -v strong_post_pivot_bars=8 -v strong_post_pivot_pct=0.06 -v strong_pre_pivot_bars=6 -v strong_pre_pivot_pct=0.12 -v target_pct=1.22 -v stop_pct=0.934 -v stop_pct_is_multiplier=true -v stop_loss_based=zone_low -v aggressive_avg_positions=18 -s "AAON,ABCB,ABG,ACA,ACU,ALG,AMD,AMN,APP,ARES,ATEYY,AU,BBW,BELFA,BWLP,CHCI,CIEN,CLS,CMC,COHR,COKE,CRS,CRWD,CSTM,CVCO,DDS,DECK,DKL,DKS,DXCM,DY,ENVA,ESP,EVR,FEIM,FN,FRD,FTAI,HWKN,IBP,IESC,IR,JOE,LMAT,LOGI,LRCX,LUGDF,LULU,MATX,MOD,MPWR,MTSI,MTZ,MYRG,NEO,NGL,NVDA,NVMI,NXPI,OR,PFSI,PLUS,POOL,POWL,PTC,QXO,RMBS,SANM,SCCO,SGI,SHOP,SIMO,SKYW,TATT,TBBK,TER,TOELY,TPH,TRT,TWLO,UHS,URI,UTI,VSEC,WDAY,WOR,XPO"

REM BRT
rem python stock_analysis\rocket_tbn.py data\newdata\data -o drive -w 16 --no-regression --aggressive --print-zones -v stop_pct=0.934 -v target_pct=1.21 -v too_high_multiplier=0 -v band_pct=0.0154 -v strong_pre_pivot_pct=0.081 -v strong_post_pivot_pct=0.108 -v strong_pre_pivot_bars=7 -v strong_post_pivot_bars=7 -v breakout_bars=100 -v tight_range_threshold_pct=0.35 -v tight_range_lookback=105 -v sheet_breakout_scan_start_row_delta=2 -v brt_sheet_touch=true -v min_spy_compare_1y_at_trigger=-1000 -v sheet_red_to_green_entry_enabled=true -v sheet_dw_countif_include_prior_bar_date=false -v growth_filter_enabled=false -v min_ind_score=-1 -v compute_beta=true -v brt_zones=true -v yh_zones=false -v min_pivot_run_h_before_entry=0 -v min_beta_at_trigger=0 -v stop_loss_based=zone_low -s "AAPL,AMD,AMZN,AU,GOOGL,META,MSFT,NFLX,NVDA,TSLA"


REM RS
rem python stock_analysis\rocket_tbn.py data\newdata\data -o drive -w 25 --no-regression --aggressive --relative-strength -v rs_mode=true -v brt_zones=false -v yh_zones=false -v wpbr_zones=false -v rl_mode=false -v target_pct=%RS_TARGET% -v stop_pct=%RS_STOP% -v stop_pct_is_multiplier=true -v use_indicators=true -v indicator_buy=off -v rs_require_tc_strong=true -v growth_filter_enabled=false -v min_spy_compare_1y_at_trigger=0 -v atr_days=0 -v too_high_multiplier=0 -v rs_max_pct_below_52w_high=0 -v rs_spy_int_tc_not_weak=false -v max_atr_pct_at_trigger=3.9 -s "AAPL,NVDA,GOOGL,MSFT,AMZN,TSM,AVGO,META,LLY,JPM,WMT,MU,AMD,V,XOM,ASML,MA"

REM SB
call run_sb -v target_pct=1.091 -v burst_max_risk_pct=0.078 -v burst_time_stop_days=5 -v burst_dcr_min=.6 -s ANAB,ARIS,AUGO,CTVA,FER,GH,HROW,REAL,SOLV,ACN,AEG,AKR,ALGM,ALL,AMG,AMTX,AN,AX,BA,BAC,BALL,BBVA,BPOP,BWA,BXP,C,CACI,CARR,CASY,CBOE,CFG,CIB,CMI,CNM,CNQ,COO,CSGP,DAL,DDS,DE,DOV,DOW,EC,EFX,EG,EHC,ENVA,ESTC,ETN,EXLS,EXR,FITB,FLS,FSI,FTI,GEHC,GNTX,GOOG,HD,HGV,IDR,IESC,IEX,IR,IRM,JPM,KEY,KR,LAUR,LII,LLY,MAS,MET,MIDD,MLI,MMS,MOH,MSTR,MTD,PCG,PH,PLPC,PNR,PTC,PVH,R,ROL,ROST,SAIC,SANM,SBGSY,SCHW,SE,SHOO,SLB,SNEX,SNX,TFX,TKO,TT,TTMI,UBS,UNM,VIRT,WBD,WBS,ZION
call run_sb -v target_pct=1.091 -v burst_max_risk_pct=0.078 -v burst_time_stop_days=5 -v burst_dcr_min=.65 -s ANAB,ARIS,AUGO,CTVA,FER,GH,HROW,REAL,SOLV,ACN,AEG,AKR,ALGM,ALL,AMG,AMTX,AN,AX,BA,BAC,BALL,BBVA,BPOP,BWA,BXP,C,CACI,CARR,CASY,CBOE,CFG,CIB,CMI,CNM,CNQ,COO,CSGP,DAL,DDS,DE,DOV,DOW,EC,EFX,EG,EHC,ENVA,ESTC,ETN,EXLS,EXR,FITB,FLS,FSI,FTI,GEHC,GNTX,GOOG,HD,HGV,IDR,IESC,IEX,IR,IRM,JPM,KEY,KR,LAUR,LII,LLY,MAS,MET,MIDD,MLI,MMS,MOH,MSTR,MTD,PCG,PH,PLPC,PNR,PTC,PVH,R,ROL,ROST,SAIC,SANM,SBGSY,SCHW,SE,SHOO,SLB,SNEX,SNX,TFX,TKO,TT,TTMI,UBS,UNM,VIRT,WBD,WBS,ZION
call run_sb -v target_pct=1.091 -v burst_max_risk_pct=0.078 -v burst_time_stop_days=5 -v burst_dcr_min=.7 -s ANAB,ARIS,AUGO,CTVA,FER,GH,HROW,REAL,SOLV,ACN,AEG,AKR,ALGM,ALL,AMG,AMTX,AN,AX,BA,BAC,BALL,BBVA,BPOP,BWA,BXP,C,CACI,CARR,CASY,CBOE,CFG,CIB,CMI,CNM,CNQ,COO,CSGP,DAL,DDS,DE,DOV,DOW,EC,EFX,EG,EHC,ENVA,ESTC,ETN,EXLS,EXR,FITB,FLS,FSI,FTI,GEHC,GNTX,GOOG,HD,HGV,IDR,IESC,IEX,IR,IRM,JPM,KEY,KR,LAUR,LII,LLY,MAS,MET,MIDD,MLI,MMS,MOH,MSTR,MTD,PCG,PH,PLPC,PNR,PTC,PVH,R,ROL,ROST,SAIC,SANM,SBGSY,SCHW,SE,SHOO,SLB,SNEX,SNX,TFX,TKO,TT,TTMI,UBS,UNM,VIRT,WBD,WBS,ZION
call run_sb -v target_pct=1.091 -v burst_max_risk_pct=0.078 -v burst_time_stop_days=5 -v burst_dcr_min=.75 -s ANAB,ARIS,AUGO,CTVA,FER,GH,HROW,REAL,SOLV,ACN,AEG,AKR,ALGM,ALL,AMG,AMTX,AN,AX,BA,BAC,BALL,BBVA,BPOP,BWA,BXP,C,CACI,CARR,CASY,CBOE,CFG,CIB,CMI,CNM,CNQ,COO,CSGP,DAL,DDS,DE,DOV,DOW,EC,EFX,EG,EHC,ENVA,ESTC,ETN,EXLS,EXR,FITB,FLS,FSI,FTI,GEHC,GNTX,GOOG,HD,HGV,IDR,IESC,IEX,IR,IRM,JPM,KEY,KR,LAUR,LII,LLY,MAS,MET,MIDD,MLI,MMS,MOH,MSTR,MTD,PCG,PH,PLPC,PNR,PTC,PVH,R,ROL,ROST,SAIC,SANM,SBGSY,SCHW,SE,SHOO,SLB,SNEX,SNX,TFX,TKO,TT,TTMI,UBS,UNM,VIRT,WBD,WBS,ZION
call run_sb -v target_pct=1.091 -v burst_max_risk_pct=0.078 -v burst_time_stop_days=5 -v burst_dcr_min=.8 -s ANAB,ARIS,AUGO,CTVA,FER,GH,HROW,REAL,SOLV,ACN,AEG,AKR,ALGM,ALL,AMG,AMTX,AN,AX,BA,BAC,BALL,BBVA,BPOP,BWA,BXP,C,CACI,CARR,CASY,CBOE,CFG,CIB,CMI,CNM,CNQ,COO,CSGP,DAL,DDS,DE,DOV,DOW,EC,EFX,EG,EHC,ENVA,ESTC,ETN,EXLS,EXR,FITB,FLS,FSI,FTI,GEHC,GNTX,GOOG,HD,HGV,IDR,IESC,IEX,IR,IRM,JPM,KEY,KR,LAUR,LII,LLY,MAS,MET,MIDD,MLI,MMS,MOH,MSTR,MTD,PCG,PH,PLPC,PNR,PTC,PVH,R,ROL,ROST,SAIC,SANM,SBGSY,SCHW,SE,SHOO,SLB,SNEX,SNX,TFX,TKO,TT,TTMI,UBS,UNM,VIRT,WBD,WBS,ZION
call run_sb -v target_pct=1.091 -v burst_max_risk_pct=0.078 -v burst_time_stop_days=5 -v burst_dcr_min=.85 -s ANAB,ARIS,AUGO,CTVA,FER,GH,HROW,REAL,SOLV,ACN,AEG,AKR,ALGM,ALL,AMG,AMTX,AN,AX,BA,BAC,BALL,BBVA,BPOP,BWA,BXP,C,CACI,CARR,CASY,CBOE,CFG,CIB,CMI,CNM,CNQ,COO,CSGP,DAL,DDS,DE,DOV,DOW,EC,EFX,EG,EHC,ENVA,ESTC,ETN,EXLS,EXR,FITB,FLS,FSI,FTI,GEHC,GNTX,GOOG,HD,HGV,IDR,IESC,IEX,IR,IRM,JPM,KEY,KR,LAUR,LII,LLY,MAS,MET,MIDD,MLI,MMS,MOH,MSTR,MTD,PCG,PH,PLPC,PNR,PTC,PVH,R,ROL,ROST,SAIC,SANM,SBGSY,SCHW,SE,SHOO,SLB,SNEX,SNX,TFX,TKO,TT,TTMI,UBS,UNM,VIRT,WBD,WBS,ZION
call run_sb -v target_pct=1.091 -v burst_max_risk_pct=0.078 -v burst_time_stop_days=5 -v burst_dcr_min=.9 -s ANAB,ARIS,AUGO,CTVA,FER,GH,HROW,REAL,SOLV,ACN,AEG,AKR,ALGM,ALL,AMG,AMTX,AN,AX,BA,BAC,BALL,BBVA,BPOP,BWA,BXP,C,CACI,CARR,CASY,CBOE,CFG,CIB,CMI,CNM,CNQ,COO,CSGP,DAL,DDS,DE,DOV,DOW,EC,EFX,EG,EHC,ENVA,ESTC,ETN,EXLS,EXR,FITB,FLS,FSI,FTI,GEHC,GNTX,GOOG,HD,HGV,IDR,IESC,IEX,IR,IRM,JPM,KEY,KR,LAUR,LII,LLY,MAS,MET,MIDD,MLI,MMS,MOH,MSTR,MTD,PCG,PH,PLPC,PNR,PTC,PVH,R,ROL,ROST,SAIC,SANM,SBGSY,SCHW,SE,SHOO,SLB,SNEX,SNX,TFX,TKO,TT,TTMI,UBS,UNM,VIRT,WBD,WBS,ZION
call run_sb -v target_pct=1.091 -v burst_max_risk_pct=0.078 -v burst_time_stop_days=5 -v burst_dcr_min=.95 -s ANAB,ARIS,AUGO,CTVA,FER,GH,HROW,REAL,SOLV,ACN,AEG,AKR,ALGM,ALL,AMG,AMTX,AN,AX,BA,BAC,BALL,BBVA,BPOP,BWA,BXP,C,CACI,CARR,CASY,CBOE,CFG,CIB,CMI,CNM,CNQ,COO,CSGP,DAL,DDS,DE,DOV,DOW,EC,EFX,EG,EHC,ENVA,ESTC,ETN,EXLS,EXR,FITB,FLS,FSI,FTI,GEHC,GNTX,GOOG,HD,HGV,IDR,IESC,IEX,IR,IRM,JPM,KEY,KR,LAUR,LII,LLY,MAS,MET,MIDD,MLI,MMS,MOH,MSTR,MTD,PCG,PH,PLPC,PNR,PTC,PVH,R,ROL,ROST,SAIC,SANM,SBGSY,SCHW,SE,SHOO,SLB,SNEX,SNX,TFX,TKO,TT,TTMI,UBS,UNM,VIRT,WBD,WBS,ZION
call run_sb -v target_pct=1.091 -v burst_max_risk_pct=0.078 -v burst_time_stop_days=5 -v burst_dcr_min=.96 -s ANAB,ARIS,AUGO,CTVA,FER,GH,HROW,REAL,SOLV,ACN,AEG,AKR,ALGM,ALL,AMG,AMTX,AN,AX,BA,BAC,BALL,BBVA,BPOP,BWA,BXP,C,CACI,CARR,CASY,CBOE,CFG,CIB,CMI,CNM,CNQ,COO,CSGP,DAL,DDS,DE,DOV,DOW,EC,EFX,EG,EHC,ENVA,ESTC,ETN,EXLS,EXR,FITB,FLS,FSI,FTI,GEHC,GNTX,GOOG,HD,HGV,IDR,IESC,IEX,IR,IRM,JPM,KEY,KR,LAUR,LII,LLY,MAS,MET,MIDD,MLI,MMS,MOH,MSTR,MTD,PCG,PH,PLPC,PNR,PTC,PVH,R,ROL,ROST,SAIC,SANM,SBGSY,SCHW,SE,SHOO,SLB,SNEX,SNX,TFX,TKO,TT,TTMI,UBS,UNM,VIRT,WBD,WBS,ZION
call run_sb -v target_pct=1.091 -v burst_max_risk_pct=0.078 -v burst_time_stop_days=5 -v burst_dcr_min=.97 -s ANAB,ARIS,AUGO,CTVA,FER,GH,HROW,REAL,SOLV,ACN,AEG,AKR,ALGM,ALL,AMG,AMTX,AN,AX,BA,BAC,BALL,BBVA,BPOP,BWA,BXP,C,CACI,CARR,CASY,CBOE,CFG,CIB,CMI,CNM,CNQ,COO,CSGP,DAL,DDS,DE,DOV,DOW,EC,EFX,EG,EHC,ENVA,ESTC,ETN,EXLS,EXR,FITB,FLS,FSI,FTI,GEHC,GNTX,GOOG,HD,HGV,IDR,IESC,IEX,IR,IRM,JPM,KEY,KR,LAUR,LII,LLY,MAS,MET,MIDD,MLI,MMS,MOH,MSTR,MTD,PCG,PH,PLPC,PNR,PTC,PVH,R,ROL,ROST,SAIC,SANM,SBGSY,SCHW,SE,SHOO,SLB,SNEX,SNX,TFX,TKO,TT,TTMI,UBS,UNM,VIRT,WBD,WBS,ZION
call run_sb -v target_pct=1.091 -v burst_max_risk_pct=0.078 -v burst_time_stop_days=5 -v burst_dcr_min=.98 -s ANAB,ARIS,AUGO,CTVA,FER,GH,HROW,REAL,SOLV,ACN,AEG,AKR,ALGM,ALL,AMG,AMTX,AN,AX,BA,BAC,BALL,BBVA,BPOP,BWA,BXP,C,CACI,CARR,CASY,CBOE,CFG,CIB,CMI,CNM,CNQ,COO,CSGP,DAL,DDS,DE,DOV,DOW,EC,EFX,EG,EHC,ENVA,ESTC,ETN,EXLS,EXR,FITB,FLS,FSI,FTI,GEHC,GNTX,GOOG,HD,HGV,IDR,IESC,IEX,IR,IRM,JPM,KEY,KR,LAUR,LII,LLY,MAS,MET,MIDD,MLI,MMS,MOH,MSTR,MTD,PCG,PH,PLPC,PNR,PTC,PVH,R,ROL,ROST,SAIC,SANM,SBGSY,SCHW,SE,SHOO,SLB,SNEX,SNX,TFX,TKO,TT,TTMI,UBS,UNM,VIRT,WBD,WBS,ZION
call run_sb -v target_pct=1.091 -v burst_max_risk_pct=0.078 -v burst_time_stop_days=5 -v burst_dcr_min=.99 -s ANAB,ARIS,AUGO,CTVA,FER,GH,HROW,REAL,SOLV,ACN,AEG,AKR,ALGM,ALL,AMG,AMTX,AN,AX,BA,BAC,BALL,BBVA,BPOP,BWA,BXP,C,CACI,CARR,CASY,CBOE,CFG,CIB,CMI,CNM,CNQ,COO,CSGP,DAL,DDS,DE,DOV,DOW,EC,EFX,EG,EHC,ENVA,ESTC,ETN,EXLS,EXR,FITB,FLS,FSI,FTI,GEHC,GNTX,GOOG,HD,HGV,IDR,IESC,IEX,IR,IRM,JPM,KEY,KR,LAUR,LII,LLY,MAS,MET,MIDD,MLI,MMS,MOH,MSTR,MTD,PCG,PH,PLPC,PNR,PTC,PVH,R,ROL,ROST,SAIC,SANM,SBGSY,SCHW,SE,SHOO,SLB,SNEX,SNX,TFX,TKO,TT,TTMI,UBS,UNM,VIRT,WBD,WBS,ZION


rem -s "CTAS,CASY,CW,BSX,FISV,HWM,PRI,CPRT,DHR,UNH,BRO,MCK,V,POOL,BR,TDY,TMO,AER,ORLY,ADBE,DECK,LOGI,PGR,CRZBY,QQQ,LII,ICE,ROL,COST,RBC,CHTR,MSCI,WST,ESE,AZO,AXSM,FINMY,MCO,DG,CDW,EA,FIVN,FICO,ENSG,SPGI,MSI,AON,PFSI,BFC,CSGP,RCL,EME,GE,CRS,PH,WAB,IBKR,ZBRA,ATEYY,CBOE,NFLX,NVDA,MSFT,SNPS,GMAB,GPN,FTI,INTU,JKHY,GNRC,ALGN,BWXT,BDGIF,META,STE,MA,IPAR,LOPE,MYRG,PWR,DSGX,POWL,RNMBY,BLX,BIO,GOOG,WDC,NXST,TMUS,ABCB,MTD,PAYC,XPO,MLI,FIX,EPAM,IDXX,AAPL,APP,AMZN"

rem -s "PVH,OLED,TORXF,RHI,NIC,JOE,OSIS,ADPT,HP,NHC,AVA,AAP,BWLP,BANC,NMIH,SBCF,LEU,VECO,MMS,SHOO,PFS,ASH,ARIS,BELFA,DHT,HWKN,AAMI,AEO,LBRT,PATK,UUUU,TBBK,ABM,APAM,AGYS,WOR,PENN,SUPN,HOG,DCO,SII,ANDE,DXPE,NG,TGB,DGII,LCII,AEHR,ATEN,WHR,BLBD,MAN,PLUS,ATUSF,MTX,HCI,AGM,HUN,BLX,LMAT,NWL,WIX,MCRI,SVM,UTI,SRCE,ALG,TGLS,NBHC,NGL,LPG,AAT,SNDX,RBCAA,NEO,INOD,EZPW,DRD,CASH,CPRI,ANIP,CTS,CYD,BFC,SRPT,DXC,ANAB,ADNT,PLPC,ATLC,ALNT,HROW,FMC,ODC,LINC,AMN,NWPX,NVAX,GHM,IRMD,WINA,OPY,XPEL,AMRC,SENEA,WLDN,ITRN,ABR,APPS,WRLD,AOSL,CCBG,LMB,ABUS,ACRS,FEIM,OMER,NGVC,TIPT,IIIN,MAKO,ANGO,TATT,ESEA,ITIC,CWCO,FRBA,IDR,BBW,PACB,CMCL,TCI,SAR,PNRG,BKTI,ESOA,KINS,FUNC,JACK,TSSI,HWBK,FRD,SNFCA,PPIH,ACU,ANIK,RCMT,PDEX,TAYD,ESP,SMID,CHCI,HURC,BLHK,AMTX,TRT,ALDX,FSI,ALBY,AHT"

rem powershell .\run_audit.ps1 -s "TSLA,AMD,INTC,XOM,LRCX,NFLX,PLTR,KLAC,WFC,ADI,STX,WDC,ANET,APP,TOELY,IBKR,CRWD,ATEYY,NEM,AEM,CNQ,FCX,FTNT,MPWR,MELI,B,FIX,RCL,GM,TER,OKE,OXY,AU,TRGP,DVN,FLEX,CCJ,ARGX,F,CLS,IDXX,EME,GFI,ARES,KGC,ESLT,STLD,MTZ,TECK,WDAY,TWLO,NRG,RMD,FOXA,FTAI,NTRA,FTI,MTSI,TPR,STRL,CFG,FOX,FSLR,ALB,FN,KEY,AKAM,TEAM,BEP,LEN,CRS,RL,DKS,AMKR,NXT"

rem python stock_analysis\BRT_DrawdownCalc.py Drive\IND_Closed_260602180527.csv 

REM LONG YH
rem python stock_analysis\rocket_tbn.py data\newdata\data -o drive -w 32 --aggressive --use-duckdb --no-regression -v yh_zones=true -v brt_zones=false -v band_pct=0.0099 -v strong_pre_pivot_pct=0.12 -v strong_post_pivot_pct=0.109 -v min_spy_compare_1y_at_trigger=-1000 -v max_atr_pct_at_trigger=1.61 -v ind_score_weights_path="" -v too_high_multiplier=0 -v yh_move_away_pct=0.031 -v target_pct=1.2 -v stop_pct=0.9 -s "NOC,RSG,FISV,ATO,AAPL,CME,COST,UNH,CTAS,RELX,TJX,NKE,BR,MSI,WRB,AEP,AJG,WM,VRSN,XEL,CPRT,ASML,CB,MO,CBOE,DHR,HRL,SO,BA,ESLT,GOOG,HD,PAYX,VRSK,LHX,NEE,ORLY,UNP,FIS,LDOS,WMT,ICE,ORI,CHKP,ITW,YUM,APH,POOL,AMGN,GPN,LMT,HWBK,BRO,V,HIG,GLW,ZTS,TECH,DPZ,WAT,ZIJMY,DG,ROP,KDP,LNT,MA,JPM,NDAQ,HON,SONY,GOOGL,CACI,CINF,FDS,FUNC,JKHY,TT,WTS,ECL,CW,IDA,GMAB,SYY,BWXT,MKC,PGR,DBSDY,MCD,EXR,WST,ABBV,SAFRY,TFX,CSX,SYK,STE,ETR,MRK,TSN,ATEYY,CDNS,NIC,SNPS,EHC,ALL,MSFT,ACGL,CMS,IT"


REM LONG IND

REM python stock_analysis\rocket_tbn.py data\newdata\data -o drive -w 16 --aggressive --no-regression -v target_pct=1.21 -v trailing_stop_increment=0 -v strong_pre_pivot_pct=0.081 -v strong_post_pivot_pct=0.109 -v atr_progress=0 -v atr_days=0 -v compute_beta=true -v min_avg_volume_10d_at_entry=0 -v min_atr_pct_at_trigger=8.1 -v max_atr_pct_at_trigger=0 -v use_indicators=true -v indicator_buy=only -v indicator_diff=11 -v indicator_sides=long -v transaction_type=long -v atr_target=2.4 -v atr_stop=1.1 -v max_ind_entry_neutral_n=29 -v yh_zones=false 

REM stock_analysis/rocket_tbn.py data/newdata/data -o drive -w 16 --aggressive --no-regression --aggressive-sizing-equity-cap=999 -v aggressive_avg_positions=6 -v target_pct=1.21 -v atr_progress=0 -v atr_days=0  -v compute_beta=false -v use_indicators=true -v indicator_buy=only -v indicator_sides=long -v transaction_type=long -v  atr_target=0 -v atr_stop=0 -v sell_ind_diff_below=0 -v exit_ind_diff_only=false -v use_ind_score=true -v use_sma50=false -v sma_stop_days=0 -v post_entry_gain_pct=10 -v post_entry_gain_calendar_days=30 -v growth_filter_enabled=false -v require_close_gt_open=false -v ind_score_weights_path=ind_score_weights_260608190347.json -v too_high_multiplier=0 -v entry_close_min_range_position=0 -v too_low_multiplier=0 -v symbol_reentry_cooldown_days=0 -v margin_utilization=1 -v max_touch_count_short=0 -v entry_filter_meteoric_rise=both -v entry_filter_meteoric_fall=both -v min_atr_pct_at_trigger=0 -v indicator_diff=-100 -v max_ind_entry_neutral_n=1000 -v min_ind_score=0 -v sell_on_low_vol=0.1 -v min_dist_to_52w_high_pct_at_trigger=0 -v min_spy_compare_1y_at_trigger=0 -v stop_pct=0.96 -v mandatory_ind_states_path=mandatory_ind_states.json

REM SHORT
rem python stock_analysis/rocket_tbn.py data/newdata/data -o drive -w 16 --aggressive --profile -v target_pct=1.21 -v trailing_stop_increment=0 -v strong_pre_pivot_pct=0.081 -v strong_post_pivot_pct=0.109 -v atr_progress=0 -v atr_days=0  -v compute_beta=true -v min_avg_volume_10d_at_entry=0 -v min_atr_pct_at_entry=7.2 -v max_atr_pct_at_entry=0 -v use_indicators=true -v indicator_buy=only -v indicator_diff=10 -v indicator_sides=short -v transaction_type=short -v short_target=1.2


REM python stock_analysis/rocket_tbn.py data/newdata/data -o drive -w 16 --aggressive --profile -v target_pct=1.21 -v trailing_stop_increment=0 -v strong_pre_pivot_pct=0.081 -v strong_post_pivot_pct=0.109 -v atr_progress=0 -v atr_days=0  -v compute_beta=true -v min_avg_volume_10d_at_entry=0 -v min_atr_pct_at_entry=7.2 -v max_atr_pct_at_entry=0 -v use_indicators=true -v indicator_buy=only -v indicator_diff=10 -s "NVDA,WDC,SHOP,NEM,CIEN,LITE,NET,B,REGN,OXY,FANG,AU,GFI,HUM,KGC,TECK,TWLO,NTRA,ZS,MDB,FN,FTAI,INSM,TEAM,WWD,EXAS,CDE,WES,DLTR,AGI,DOCN,OKTA,RGC,APA,SGI,UNM,BBIO,GH,BBY,APLD,MDGL,SANM,U,AXSM,VIRT


rem python stock_analysis/rocket_tbn.py data/newdata/data -o drive -w 16 --aggressive -v target_pct=1.21 -v trailing_stop_increment=0 -v strong_pre_pivot_pct=0.081 -v strong_post_pivot_pct=0.109 -v atr_progress=0 -v atr_days=0  -v compute_beta=true -v min_avg_volume_10d_at_entry=0 -v min_atr_pct_at_entry=2 -v max_market_cap=111111164166115120 -v post_entry_gain_pct=20 -v post_entry_gain_calendar_days=75 -v sheet_dw_countif_include_prior_bar_date=false --print-zones  -v atr_progress_incremental_stop=false -v stop_pct=0.903 -v too_high_multiplier=1.058 -v band_pct=0.017 -v short_target_pct=1.18 -v transaction_type=long -v entry_type=long -v growth_filter_enabled=true -v short_stop_pct=0.95 -v use_indicators=true -v indicator_buy=only -s "AAPL,ABBV,ACN,ADBE,ADI,AMAT,AMD,AMZN,AU,AVGO,AXP,BABA,BAC,CDNS,CI,CRM,CRWD,DIS,GILD,GOOG,GOOGL,HD,JPM,KO,KR,LOW,LYV,META,MPC,MS,MSFT,MU,NEM,NFLX,NVDA,ORCL,PFE,PG,PLTR,PM,PPTA,SHOP,TMUS,TSLA,TSM,UNH,V,WFC,WMT,XOM" 

rem python stock_analysis/rocket_tbn.py data/newdata/data -o drive -w 16 --aggressive -v target_pct=1.21 -v trailing_stop_increment=0 -v strong_pre_pivot_pct=0.081 -v strong_post_pivot_pct=0.109 -v atr_progress=0 -v atr_days=0  -v compute_beta=true -v min_avg_volume_10d_at_entry=0 -v min_atr_pct_at_entry=2 -v max_market_cap=111111164166115120 -v post_entry_gain_pct=20 -v post_entry_gain_calendar_days=75 -v sheet_dw_countif_include_prior_bar_date=false --print-zones  -v atr_progress_incremental_stop=false -v stop_pct=0.903 -v too_high_multiplier=1.058 -v band_pct=0.017 -v short_target_pct=1.18 -v transaction_type=long -v entry_type=long -v growth_filter_enabled=true -v short_stop_pct=0.95 -v use_indicators=true -v indicator_buy=only -v indicator_diff=10

REM RL Markten


rem python stock_analysis\rocket_brt.py data\newdata\data -o drive -w 10 --aggressive --no-regression -v rl_mode=true -v brt_zones=false -v yh_zones=false -v indicator_buy=off -v rl_sma_qual=1 -v ATR_LOW=off -v ATR_HIGH=off -v rl_slope_threshold=0 -v rl_dip_pct=1.041 -v rl_too_high=0  -v rl_target_pct=1.2 -v rl_post_target_reentry_bars=10 -v rl_post_target_reentry_mode=under_sma_limit -v rl_post_target_under_sma20=0.01 -s "MTZ,NXT,APP,SAIA,NFLX,HUBS,FIVN,AGX,HCI,GHM,MU,AMAT,WRLD,RNG,CF,STX,GLW,LMAT,LMND,DXPE,LMB,EXEL,NGVC,AU,AGI,AA,TGB,PDEX,GFI,UTI,NTRA,STLD,TORXF,DOCN,FN,VLO,INOD,AMD,TTMI,SPRY,BBW,CRWD,TPC,AX,AEHR,ANIP,PSIX,AEM,KINS,MOD,EDVMF,WDC,TGLS,CMCL,CORT,NVAX,AMKR,PATK,ABUS"

