python stock_analysis\rocket_brt.py --symbol AAL
python stock_analysis\rocket_brt.py --symbol AAPL
python stock_analysis\rocket_brt.py --symbol AMZN
python stock_analysis\rocket_brt.py --symbol ANF
python stock_analysis\rocket_brt.py --symbol AU
python stock_analysis\rocket_brt.py --symbol CDE
python stock_analysis\rocket_brt.py --symbol CLF
python stock_analysis\rocket_brt.py --symbol CORT
python stock_analysis\rocket_brt.py --symbol ESEA
python stock_analysis\rocket_brt.py --symbol EXTR
python stock_analysis\rocket_brt.py --symbol FANG
python stock_analysis\rocket_brt.py --symbol Googl
python stock_analysis\rocket_brt.py --symbol META
python stock_analysis\rocket_brt.py --symbol MOS
python stock_analysis\rocket_brt.py --symbol MSFT
python stock_analysis\rocket_brt.py --symbol NFLX
python stock_analysis\rocket_brt.py --symbol NVDA
python stock_analysis\rocket_brt.py --symbol SBS
python stock_analysis\rocket_brt.py --symbol SHOP
python stock_analysis\rocket_brt.py --symbol SNDX
python stock_analysis\rocket_brt.py --symbol TGS
python stock_analysis\rocket_brt.py --symbol TSLA
python stock_analysis\rocket_brt.py --symbol UUUU
