"""
Stable column order for BRT_Report / BRT_Audit_Report / BRT_Audit_Report_RL and optimizer.

Single shared Audit schema for all systems (BRT / YH / RS / RL / WPBR / IND / MTS /
VEC / MVCP / SB / QULL / VZ / WRL). System-specific levers (``mvcp_*``, ``sb_mode`` / ``burst_*``,
``qull_*``, ``vz_*``, ``wrl_*``, …) are always present; non-active systems leave them blank (see
``rocket_tbn._fill_sb_mode_audit`` / ``_fill_mvcp_mode_audit`` / ``_fill_qull_mode_audit`` /
``_fill_vz_mode_audit`` / ``_fill_wrl_mode_audit``).

Trade-level IND / Trading Central horizon fields (``IND_*``, ``IND_TC_*``) are **not** listed
here — they append to Closed / Open / Scanner via ``brt_entry_indicators.entry_indicator_csv_headers``
when ``use_indicators`` is on (report/audit only for ``IND_TC_*``; no entry gates).
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Any, Mapping

# Exact header order for all ``*_Audit_Report_*.csv`` / Report wide rows.
_BRT_AUDIT_COLUMN_ORDER: tuple[str, ...] = (
    "Timestamp_Drive",
    "pivot_k",
    "pivot_d",
    "pivot_disp",
    "pivot_m",
    "band_pct",
    "lookback_long",
    "touch_threshold",
    "strong_pivots_enabled",
    "strong_pre_pivot_bars",
    "strong_pre_pivot_pct",
    "strong_post_pivot_bars",
    "strong_post_pivot_pct",
    "strong_pivot_mode",
    "zone_include_pre_strong_pivot_lows",
    "zones_from_pivot_lows_enabled",
    "brt_zones",
    "yh_zones",
    "wpbr_zones",
    "wpbr_breakout_confirmation",
    "wpbr_max_days_after_retest",
    "wpbr_second_chance_after_win",
    "wpbr_merge_overlapping_zones",
    "mts_mode",
    "rs_mode",
    "mvcp_mode",
    "mvcp_rs_min_percentile",
    "mvcp_rs_lookback",
    "mvcp_sma200_rise_bars",
    "mvcp_min_pct_above_52w_low",
    "mvcp_max_pct_below_52w_high",
    "mvcp_min_contractions",
    "mvcp_max_contractions",
    "mvcp_swing_k",
    "mvcp_depth_shrink",
    "mvcp_max_first_depth",
    "mvcp_min_final_depth",
    "mvcp_min_base_bars",
    "mvcp_max_base_bars",
    "mvcp_vol_dry_ratio",
    "mvcp_vol_dry_soft_confirm",
    "mvcp_require_prior_advance",
    "mvcp_prior_advance_pct",
    "mvcp_prior_advance_bars",
    "mvcp_vol_breakout_mult",
    "mvcp_max_extension_above_pivot",
    "mvcp_stop_eps",
    "mvcp_strength_pct",
    "mvcp_strength_bars",
    "mvcp_trail_sma",
    "mvcp_trail_arm_pct",
    "mvcp_time_stop_bars",
    "mvcp_time_stop_min_gain",
    "mvcp_rs_universe",
    "qull_mode",
    "qull_setup",
    "qull_prior_run_bars",
    "qull_prior_run_pct",
    "qull_coil_bars",
    "qull_coil_range_pct",
    "qull_ema_surf_pct",
    "qull_require_ema_surf",
    "qull_vol_dry_ratio",
    "qull_vol_dry_soft",
    "qull_vol_breakout_mult",
    "qull_min_price",
    "qull_min_adv_usd",
    "qull_adv_lookback",
    "qull_market_filter",
    "qull_ep_gap_pct",
    "qull_ep_vol_mult",
    "qull_ep_require_flat_prior",
    "qull_ep_flat_lookback",
    "qull_ep_flat_max_run_pct",
    "qull_stop_under",
    "qull_max_stop_adr_mult",
    "qull_adr_lookback",
    "qull_trail_ema",
    "qull_partial_days",
    "qull_partial_frac",
    "qull_fill",
    "qull_require_above_sma50",
    "qull_require_sma50_rising",
    "qull_sma50_slope_bars",
    "qull_require_above_sma20",
    "qull_require_above_sma10",
    "vz_mode",
    "vz_lookback_days",
    "vz_retest_window",
    "vz_retest_eps_pct",
    "vz_first_retest_only",
    "vz_min_touches_before_entry",
    "vz_entry_on",
    "vz_zone_kinds",
    "vz_exit_name",
    "vz_exit_bars",
    "vz_target_r",
    "vz_stop_atr_buffer",
    "vz_min_atr_pct_at_entry",
    "vz_require_hvn_overlap",
    "vz_sheet_notional",
    "wrl_mode",
    "wrl_target_mode",
    "wrl_scale_frac",
    "wrl_min_zone_pct",
    "wrl_min_rr",
    "wrl_min_rr_target",
    "wrl_time_stop_bars",
    "rl_mode",
    "rl_sma_qual",
    "rl_dip_pct",
    "rl_50_sma_lookback",
    "rl_expansion",
    "rl_expansion_lookback_days",
    "rl_acc_min",
    "rl_acc_count",
    "rl_cut_the_losers",
    "rl_atr_low_percent",
    "rl_atr_high_percent",
    "rl_atr_high_value",
    "rl_low_price",
    "rl_peak_threshold_max",
    "rl_slope_period",
    "rl_slope_threshold",
    "rl_shock_threshold",
    "rl_shock_rehab_days",
    "rl_shock_max_allowed",
    "rl_too_high",
    "rl_spy_inclusion",
    "rl_avg_vol_days",
    "rl_vol_pct_threshold",
    "rl_brt_entry_gates_enabled",
    "rl_stop_pct",
    "rl_post_target_reentry_bars",
    "rl_post_target_reentry_mode",
    "rl_post_target_stop_pct",
    "rl_post_target_min_stack",
    "rl_post_target_under_sma20",
    "rl_target_pct",
    "rl_trail_profit",
    "rl_trail_stop",
    "rl_trail_profit2",
    "rl_trail_stop2",
    "rl_exit_percent",
    "rl_exit_days",
    "rl_flush_days",
    "rl_partial_exit_target",
    "rl_partial_exit_percent",
    "rl_partial_exit_follow_target",
    "rl_watch_min_score",
    "rl_watch_disable",
    "rl_cash",
    "rl100_toggle",
    "rl100_cash",
    "rl100_dip_pct",
    "rl100_expansion",
    "rl100_acc_min",
    "rl100_acc_count",
    "rl100_too_high",
    "rl100_trail_profit",
    "rl100_trail_stop",
    "rl100_trail_profit2",
    "rl100_trail_stop2",
    "rl100_target_pct",
    "rl100_stop_pct",
    "rl100_exit_percent",
    "rl100_exit_days",
    "rl100_slope_period",
    "rl100_slope_threshold",
    "rl100_100_sma_lookback",
    "rl100_cut_the_losers",
    "rl100_flush_days",
    "rl100_spy_inclusion",
    "rl100_partial_exit_target",
    "rl100_partial_exit_percent",
    "rl100_partial_exit_follow_target",
    "rl100_atr_high_percent",
    "rl100_atr_low_percent",
    "rl100_atr_high_value",
    "rl100_low_price",
    "db_toggle",
    "db_cash",
    "db_stop_pct",
    "db_target_pct",
    "db_rip_days_min",
    "db_rip_days_max",
    "db_rip_touch_tol",
    "db_max_hold_days",
    "db_squeeze_exit",
    "db_inverse_strict",
    "db_slope_lookback",
    "db_gap_up_max",
    "db_expansion",
    "db_acc_min",
    "db_acc_count",
    "db_peak_trough_max",
    "yh_lookback",
    "yh_move_away_pct",
    "yh_memory_mode",
    "yh_serial_memory",
    "close_above_window",
    "row_local_eval_ttl_bars_after_first_eval",
    "level_acceptance_window",
    "level_acceptance_required",
    "support_test_enabled",
    "breakout_bars",
    "tight_range_enabled",
    "tight_range_threshold_pct",
    "tight_range_lookback",
    "tradeable_key_level_enabled",
    "lookback_short",
    "min_touch_count",
    "max_touch_count_minor",
    "min_pivot_run_l_before_entry",
    "min_pivot_run_h_before_entry",
    "min_rel_vol_at_entry",
    "min_market_cap",
    "max_market_cap",
    "min_hist_ann_ror_avg",
    "min_avg_volume_10d_at_entry",
    "min_atr_pct_at_trigger",
    "max_atr_pct_at_trigger",
    "min_dist_to_52w_high_pct_at_trigger",
    "max_dist_to_52w_high_pct_at_trigger",
    "min_spy_compare_1y_at_trigger",
    "max_spy_compare_1y_at_trigger",
    "min_spy_compare_2y_at_trigger",
    "min_spy_compare_3y_at_trigger",
    "min_beta_at_trigger",
    "max_beta_at_trigger",
    "min_upper_wick_atr_at_trigger",
    "pivot_switch_h_to_l_filter",
    "entry_filter_major_pivot",
    "entry_filter_is_20bar_high_at_trigger",
    "entry_filter_meteoric_rise",
    "entry_filter_meteoric_fall",
    "growth_filter_enabled",
    "growth_bars",
    "entry_close_min_range_position",
    "sheet_maturity_lag_bars",
    "displacement_filter_enabled",
    "displacement_rolling_bars",
    "displacement_threshold_pct",
    "consolidation_blocker_enabled",
    "cb_max_box_width_pct",
    "brt_cash",
    "capacity_brt_cash",
    "effective_brt_cash",
    "sheet_brt_cash",
    "stop_pct",
    "stop_pct_is_multiplier",
    "target_pct",
    "atr_target",
    "atr_stop",
    "trailing_stop_increment",
    "atr_progress",
    "atr_days",
    "no_ft_days",
    "time_stop_days",
    "realtime_filter_enabled",
    "realtime_filter_threshold",
    "realtime_filter_use_zscore",
    "weight_touch_count_minor",
    "weight_zone_cluster_density",
    "weight_nearby_zones_above",
    "weight_touch_count_major",
    "weight_pct_entry_to_bottom_zone_above",
    "weight_z_score_at_trigger",
    "weight_pivot_run_l_before_entry",
    "weight_nearby_zones_below",
    "weight_pct_drop_to_top_zone_below",
    "weight_rel_vol_at_entry",
    "weight_displacement_pct_at_entry",
    "weight_lower_wick_atr_at_trigger",
    "weight_growth_pct_over_period",
    "weight_beta_at_entry",
    "days_per_year",
    "exit_at_close_when_stopped",
    "compute_equity_metrics",
    "pending_max_bars",
    "entry_eval_mode",
    "row_local_eval_touch_same_bar",
    "row_local_require_active_context_match",
    "level_acceptance_anchor_mode",
    "level_acceptance_anchor_window",
    "sheet_dw_countif_entry_enabled",
    "sheet_dw_countif_include_prior_bar_date",
    "retest_multi_zone_pick",
    "breakout_zone_pick",
    "entry_retest_bullish_growth_only",
    "do_gate_enabled",
    "do_good_for_bars",
    "dp_gate_enabled",
    "dp_window_bars",
    "dp_good_for_bars",
    "sheet_magic_touch_enabled",
    "sheet_magic_touch_window_bars",
    "initial_capital",
    "aggressive",
    "aggressive_margin_interest",
    "aggressive_max_multiple",
    "aggressive_avg_positions",
    "aggressive_avg_positions_actual",
    "aggressive_sizing_equity_cap",
    "aggressive_sell",
    "margin_utilization",
    "symbol_reentry_cooldown_days",
    "Param_Name",
    "Param_Value",
    "Total_PNL",
    "capacity_Total_PNL",
    "effective_Total_PNL",
    "sheet_PnL",
    "Wins",
    "Losses",
    "BE",
    "Pct_Wins",
    "Pct_Losses",
    "Win_Loss_Ratio",
    "Win_Loss_Ratio_Dollar",
    "Total_Trades",
    "Profit_Factor",
    "Avg_Win_Pct",
    "Avg_Loss_Pct",
    "Avg_PNL_Pct",
    "Expectancy",
    "Expectancy_Pct",
    "Avg_Days_Held",
    "Median_Days_Held",
    "P90_Days",
    "Avg_Days_Underwater",
    "P90_Days_Underwater",
    "Capital_Days",
    "Profit_Per_Capital_Day",
    "Ann_ROR",
    "Max_DD",
    "Losing_Streak",
    "DD_Per_Trade",
    "CES_AVG",
    "CES_Median",
    "Pct_PNL_Top10",
    "Pct_PNL_Bottom10",
    "Max_Positions",
    "Avg_Positions",
    "Median_Positions",
    "Score",
    "zone_maturity_model",
    "sheet_di_breakout_price",
    "sheet_di_max_history_bars",
    "compute_beta",
    "relative_strength_enabled",
    "rs_require_tc_strong",
    "rs_max_pct_below_52w_high",
    "rs_spy_int_tc_not_weak",
    "spy_int_tc_lag",
    "spy_tc_weak_horizon",
    "block_entries_when_spy_int_weak",
    "exit_when_spy_int_turns_weak",
    "meteoric_rise_pct",
    "meteoric_rise_lookback",
    "meteoric_fall_pct",
    "meteoric_fall_lookback",
    "post_entry_gain_pct",
    "post_entry_gain_calendar_days",
    "Pct_PNL_Max_Symbol",
    "Pct_PNL_Max_Trade",
    "Pct_PNL_Max_Industry",
    "Aggressive_Total_PNL",
    "Aggressive_Max_DD",
    "Aggressive_Avg_Positions",
    "Aggressive_Days_AtOrBelow_Avg",
    "Aggressive_Days_In_Margin",
    "Aggressive_Days_Trimmed_Over_2xAvg",
    "Trades_With_Meteoric_Rise_History",
    "Pct_Trades_With_Meteoric_Rise_History",
    "Trades_With_Meteoric_Fall_History",
    "Pct_Trades_With_Meteoric_Fall_History",
    "Trades_Post_Entry_Gain_Hit",
    "Pct_Trades_Post_Entry_Gain_Hit",
    "band_pct_atr",
    "strong_pre_pivot_pct_atr",
    "strong_post_pivot_pct_atr",
    "max_touch_count_short",
    "max_ind_entry_neutral_n",
    "min_ind_entry_bull_n",
    "max_ind_diff_at_trigger",
    "entry_start_date",
    "entry_end_date",
    "use_indicators",
    "use_ind_score",
    "ind_score_weights_path",
    "min_ind_score",
    "mandatory_ind_states_path",
    "exclude_ind_states_path",
    "indicator_buy",
    "indicator_diff",
    "sell_ind_diff_below",
    "exit_ind_diff_only",
    "indicator_sides",
    "transaction_type",
    "entry_type",
    "zone_role_mode",
    "zone_role_override",
    "short_stop_pct",
    "short_target_pct",
    "too_high_multiplier",
    "too_low_multiplier",
    "atr_progress_incremental_stop",
    "sb_mode",
    "burst_min_pct",
    "burst_vol_gt_prior",
    "burst_range_lookback",
    "burst_dcr_min",
    "burst_max_prior_up_days",
    "burst_fill",
    "burst_max_risk_pct",
    "burst_time_stop_days",
    "burst_no_ft_days",
    "burst_mm_gate",
    "burst_mm_min_ratio",
    "mm_min_shares",
    "mm_min_adv_usd",
    "mm_min_price",
    "mm_move_pct",
    "mm_lookback",
    "mm_force_rebuild",
    "burst_require_t1_narrow_or_down",
    "burst_t1_narrow_mode",
    "burst_min_price",
    "burst_min_adv_usd",
    "burst_adv_lookback",
    "burst_size_from_stop",
    "burst_risk_frac",
    "burst_min_atr_pct_at_trigger",
    "burst_max_atr_pct_at_trigger",
    "burst_min_dist_to_52w_high_pct",
    "burst_max_dist_to_52w_high_pct",
    "burst_vol_vs_avg_mult",
    "burst_vol_avg_lookback",
    "host_dollar_scale",
    "sb_gold_universe",
    "sb_signals_total",
    "sb_rejected_fills_total",
    "sb_rejected_too_low",
    "sb_rejected_too_high",
    "sb_rejected_mm",
    "sb_rejected_t1_n",
    "sb_rejected_vol_vs_avg",
    "sheet_touch_pullback_bars",
    "vec_zones",
    "vec_vp_lookback",
    "vec_vp_bin_pct",
    "vec_prior_bars",
    "vec_prior_side",
    "vec_confluence_pct",
    "vec_move_away_pct",
    "vec_min_bars_between",
    "wpbr_retest_mode",
    "rl_charts",
    "rl_deep_analysis",
    "sell_on_low_vol",
    "min_zone_above_pct",
    "require_no_zone_above",
    "zone_exits",
    "zone_exits_union",
    "zone_rr_min",
    "growth_history_slack_bars",
    "require_close_gt_open",
    "sheet_red_to_green_entry_enabled",
    "backtest_end_date",
    "sheet_no_entry_same_bar_after_exit",
    "sell_breakdown",
    "entry_mode",
    "adx_period",
    "adx_max",
    "channel_length",
    "pending_stop_bars",
    "stop_order_gap_fill_at_open",
    "stop_loss_based",
    "stop_anchor",
    "target_enabled",
    "use_sma50",
    "sma_stop_days",
    "chandelier_enabled",
    "chandelier_atr_period",
    "chandelier_atr_mult",
    "zscore_exit_enabled",
    "zscore_exit_lookback",
    "zscore_exit_k",
    "slippage_bps",
    "commission_per_trade",
    "liquidate_at_end",
    "max_positions",
    "allow_secondary_entries",
)

# StockBee-only levers (blank when sb_mode is false).
_SB_AUDIT_LEVER_COLS: tuple[str, ...] = (
    "sb_mode",
    "burst_min_pct",
    "burst_vol_gt_prior",
    "burst_range_lookback",
    "burst_dcr_min",
    "burst_max_prior_up_days",
    "burst_fill",
    "burst_max_risk_pct",
    "burst_time_stop_days",
    "burst_no_ft_days",
    "burst_mm_gate",
    "burst_mm_min_ratio",
    "mm_min_shares",
    "mm_min_adv_usd",
    "mm_min_price",
    "mm_move_pct",
    "mm_lookback",
    "mm_force_rebuild",
    "burst_require_t1_narrow_or_down",
    "burst_t1_narrow_mode",
    "burst_min_price",
    "burst_min_adv_usd",
    "burst_adv_lookback",
    "burst_size_from_stop",
    "burst_risk_frac",
    "burst_min_atr_pct_at_trigger",
    "burst_max_atr_pct_at_trigger",
    "burst_min_dist_to_52w_high_pct",
    "burst_max_dist_to_52w_high_pct",
    "burst_vol_vs_avg_mult",
    "burst_vol_avg_lookback",
    "host_dollar_scale",
    "sb_gold_universe",
    "sb_signals_total",
    "sb_rejected_fills_total",
    "sb_rejected_too_low",
    "sb_rejected_too_high",
    "sb_rejected_mm",
    "sb_rejected_t1_n",
    "sb_rejected_vol_vs_avg",
)

# Minervini VCP-only levers (blank when mvcp_mode is false).
_MVCP_AUDIT_LEVER_COLS: tuple[str, ...] = (
    "mvcp_mode",
    "mvcp_rs_min_percentile",
    "mvcp_rs_lookback",
    "mvcp_sma200_rise_bars",
    "mvcp_min_pct_above_52w_low",
    "mvcp_max_pct_below_52w_high",
    "mvcp_min_contractions",
    "mvcp_max_contractions",
    "mvcp_swing_k",
    "mvcp_depth_shrink",
    "mvcp_max_first_depth",
    "mvcp_min_final_depth",
    "mvcp_min_base_bars",
    "mvcp_max_base_bars",
    "mvcp_vol_dry_ratio",
    "mvcp_vol_dry_soft_confirm",
    "mvcp_require_prior_advance",
    "mvcp_prior_advance_pct",
    "mvcp_prior_advance_bars",
    "mvcp_vol_breakout_mult",
    "mvcp_max_extension_above_pivot",
    "mvcp_stop_eps",
    "mvcp_strength_pct",
    "mvcp_strength_bars",
    "mvcp_trail_sma",
    "mvcp_trail_arm_pct",
    "mvcp_time_stop_bars",
    "mvcp_time_stop_min_gain",
    "mvcp_rs_universe",
)

# Qullamaggie HTF/EP-only levers (blank when qull_mode is false).
_QULL_AUDIT_LEVER_COLS: tuple[str, ...] = (
    "qull_mode",
    "qull_setup",
    "qull_prior_run_bars",
    "qull_prior_run_pct",
    "qull_coil_bars",
    "qull_coil_range_pct",
    "qull_ema_surf_pct",
    "qull_require_ema_surf",
    "qull_vol_dry_ratio",
    "qull_vol_dry_soft",
    "qull_vol_breakout_mult",
    "qull_min_price",
    "qull_min_adv_usd",
    "qull_adv_lookback",
    "qull_market_filter",
    "qull_ep_gap_pct",
    "qull_ep_vol_mult",
    "qull_ep_require_flat_prior",
    "qull_ep_flat_lookback",
    "qull_ep_flat_max_run_pct",
    "qull_stop_under",
    "qull_max_stop_adr_mult",
    "qull_adr_lookback",
    "qull_trail_ema",
    "qull_partial_days",
    "qull_partial_frac",
    "qull_fill",
    "qull_require_above_sma50",
    "qull_require_sma50_rising",
    "qull_sma50_slope_bars",
    "qull_require_above_sma20",
    "qull_require_above_sma10",
)

# Volume Zone-only levers (blank when vz_mode is false).
_VZ_AUDIT_LEVER_COLS: tuple[str, ...] = (
    "vz_mode",
    "vz_lookback_days",
    "vz_retest_window",
    "vz_retest_eps_pct",
    "vz_first_retest_only",
    "vz_min_touches_before_entry",
    "vz_entry_on",
    "vz_zone_kinds",
    "vz_exit_name",
    "vz_exit_bars",
    "vz_target_r",
    "vz_stop_atr_buffer",
    "vz_min_atr_pct_at_entry",
    "vz_require_hvn_overlap",
    "vz_sheet_notional",
)

# Weekly Range / Swing-only levers (blank when wrl_mode is false).
_WRL_AUDIT_LEVER_COLS: tuple[str, ...] = (
    "wrl_mode",
    "wrl_target_mode",
    "wrl_scale_frac",
    "wrl_min_zone_pct",
    "wrl_min_rr",
    "wrl_min_rr_target",
    "wrl_time_stop_bars",
)


def get_brt_audit_column_order() -> tuple[str, ...]:
    """Return full audit header order (immutable tuple)."""
    return _BRT_AUDIT_COLUMN_ORDER


def get_sb_audit_lever_cols() -> tuple[str, ...]:
    """StockBee-only Audit columns (blank on non-SB runs)."""
    return _SB_AUDIT_LEVER_COLS


def get_mvcp_audit_lever_cols() -> tuple[str, ...]:
    """MVCP-only Audit columns (blank on non-MVCP runs)."""
    return _MVCP_AUDIT_LEVER_COLS


def get_qull_audit_lever_cols() -> tuple[str, ...]:
    """Qull-only Audit columns (blank on non-Qull runs)."""
    return _QULL_AUDIT_LEVER_COLS


def get_vz_audit_lever_cols() -> tuple[str, ...]:
    """Volume Zone-only Audit columns (blank on non-VZ runs)."""
    return _VZ_AUDIT_LEVER_COLS


def get_wrl_audit_lever_cols() -> tuple[str, ...]:
    """Weekly Range / Swing-only Audit columns (blank on non-WRL runs)."""
    return _WRL_AUDIT_LEVER_COLS


def empty_audit_row() -> dict[str, str]:
    """Wide Audit row with every shared column present and empty."""
    return {c: "" for c in _BRT_AUDIT_COLUMN_ORDER}


def write_wide_audit_csv(path: str | Path, row: Mapping[str, Any]) -> Path:
    """Write one wide Audit row in shared column order (missing keys → empty)."""
    path = Path(path)
    headers = list(_BRT_AUDIT_COLUMN_ORDER)
    values = [row.get(c, "") for c in headers]
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(headers)
        w.writerow(values)
    return path

