#!/usr/bin/awk -f

# ==========================================================================================
# 100% COMPREHENSIVE VARIABLE REGISTRY & TECHNICAL DOCUMENTATION
# ------------------------------------------------------------------------------------------
# COMMAND LINE ARGUMENTS (Passed via -v)
# DEBUG_SYM:         Optional. If provided (e.g., "HMY"), triggers verbose tracing.
# RS_DAYS:            The number of trading days used to calculate Relative Strength.
# ADD_PCT:            The multiplier used for LVP programmatic additions (e.g., 0.33).
# RL_CASH:            Rocket Launcher investment amount (e.g., 50000).
# RL_DIP_PCT:        Dip threshold multiplier (e.g., 1.02 for 2%).
# RL_STOP_PCT:      Stop loss multiplier (e.g., 0.95 for 5%).
# RL_TARGET_PCT:   Profit target multiplier (e.g., 1.20 for 20%).
# SMA_QUAL:           Toggle for SMA Qualifier (1=On, 0=Off).
#
# LOCAL CALCULATION VARIABLES
# iso:                    The ISO date string (YYYYMMDD) currently being processed in the loop.
# cq:                     Current Quantity: Literal shares sold on 'iso' according to History.
# crs:                    Current RS State: 1 if (Ticker N-day Return > SPY N-day Return), else 0.
# imp:                    Impact: The dollar Alpha generated by a specific Veto decision.
# ticker_ret:         The trailing N-day percentage return calculated for the symbol.
# spy_ret:              The trailing N-day percentage return calculated for the SPY benchmark.
# exit_p:               The programmatic execution price (Opening Price of the day AFTER a signal).
# next_iso:            The ISO date of the trading day following the current signal.
# anchor:               The price reference used for the cycle's final Tactical Buy/Sell math.
# val:                    Temporary variable used to store the result of a single TAC calculation.
# pure_bh:              PNL of ONLY the initial day's shares held until the final weighted exit.
# all_buys_bh:        PNL of ALL shares bought in a cycle held until the final weighted exit.
# rs_buy_val[]:      PNL for the strategy that only buys additions if yesterday was an RS day.
# rs_sell_val[]:     PNL for the strategy (Initial entry only) that only sells interim if yesterday was NOT RS.
#
# PHASE 1: HISTORY MAPPING (Truth Baseline)
# act_syms[]:         Master list of all tickers traded. [Key: Symbol] -> [Value: 1].
# t_idx[]:              Counter for trade cycles per stock (buy-to-zero). Ex: t_idx["HMY"] = 2.
# tid:                    Unique ID for a specific trade cycle (e.g., "HMY_1").
# t_to_s[]:            Reverse lookup mapping tid back to the Ticker Symbol.
# st_iso[]:            First Buy date for a tid (YYYYMMDD).
# en_iso[]:            The day inventory hit zero for a tid (YYYYMMDD).
# h_exact_inv[]:     Daily share balance calculated from History transactions.
# h_exact_sell_q:   Quantity of shares sold on a specific date in History.
# h_exact_sell_p:   Manual execution price from History for that sale.
# hb_q/p/iso:         Raw transaction data for replay of filtered entry strategies.
# hs_q/p/iso:         Raw transaction data for replay of filtered entry strategies.
# b_cnt[]/s_cnt[]: Counters for tactically relevant buys and sells within a tid.
# tb_q[]/tb_p[]:     Tactical Buy quantity and price arrays for TAC efficiency math.
# ts_q[]/ts_p[]:     Tactical Sell quantity and price arrays for TAC efficiency math.
# ts_iso[]:            The ISO date of a tactical sell, used to filter out exit-day trades.
# initial_entry_qty[]: Total shares purchased ONLY on the very first day of a cycle.
# initial_entry_cost[]:Total dollar cost ONLY for the first day's purchases.
# total_bought_qty[]:   Total shares purchased across ALL buy actions in a cycle.
# total_bought_cost[]: Total dollar cost across ALL buy actions in a cycle.
# m_pnl[]:              The actual manual P&L calculated purely from History rows.
# is_closed[]:        1 if the cycle hit zero inventory; 0 if the position is currently open.
# h_rec_cnt:           Running count of records processed from the History file.
# hist_exit_p[]:     The weighted average price from the final day of actions for a tid.
# hist_entry_p[]:   The weighted average price from the entry day of a tid.
# sum_exit_val[]:   Accumulator for total dollars on the closing day (for weighted avg).
# sum_exit_qty[]:   Accumulator for total shares on the closing day (for weighted avg).
# sum_entry_val[]: Accumulator for total dollars on the entry day (for weighted avg).
# sum_entry_qty[]: Accumulator for total shares on the entry day (for weighted avg).
#
# PHASE 2: BENCHMARKING (SPY)
# spy_p[iso]:         Closing price of SPY for a specific date (ISO).
# spy_s[index]:      Chronological sequence of dates for SPY (for lookbacks).
# spy_idx[iso]:      Mapping of date to its chronological position index in the SPY file.
# spy_rec_cnt:        Total records processed from the SPY file.
#
# PHASE 3: PRICE SCOUTING (Symbol CSVs)
# dates[sym,ptr]: Chronological array of all dates found in a Symbol CSV.
# d_ptr[sym]:         Pointer for the chronological date array for a symbol.
# raw_op[sym,iso]:Opening price for a specific symbol and date.
# raw_cl[sym,iso]:Closing price for a specific symbol and date.
# raw_hi[sym,iso]:High price for a specific symbol and date.
# term_anchor[]:   Programmatic price found on en_iso. Found via scouting or Veto exit.
# scout_rec_cnt:   Running count of raw price rows processed across all tickers.
# prev_file:           Internal variable used to detect when awk moves to a new CSV.
# cur_s:                 The ticker symbol currently being audited.
# seen[]:               Dedup map for dates within a file.
# iso_idx[]:           Mapping of date to its pointer index within a ticker file.
#
# PHASE 4: ACCOUNTING (The Audit Loop)
# streak:               1 = Active Veto (Audit is "holding" shares due to RS).
# last_tid:            Caches the Trade ID to allow streaks to outlive history windows.
# s_q[iso]:            Shares captured on a specific date during a veto streak.
# s_p[iso]:            Manual sell price from History for the captured shares.
# s_fv[iso]:           Flag indicating if a captured sell was a "Full Exit" (Inv=0).
# fv_ledger[]:        Dollar impact of Full Veto decisions per tid.
# pv_ledger[]:        Dollar impact of Partial Veto decisions per tid.
# lvp_ledger[]:      Dollar impact of Low Value Purchase decisions per tid.
# diag[]:               Forensic math accumulator for the final log. [Key: Sym] -> [Value: Log].
# trace[]:              Row-by-row logic heartbeat for DEBUG_SYM.
# acc_rec_cnt:        Total count of ticker files successfully processed by the Accountant.
# hist_rs[]:           Map of RS state for every ticker and trading date.
#
# SUMMARY ACCUMULATORS & ITERATORS
# tm, tvb, tvs:      Final System Totals for PnL, Tactical Buy, Tactical Sell.
# tpbh, tabh:         Final System Totals for Pure B&H and All Buys B&H.
# trsb, trss:         Final System Total for RS-Filtered Buy and RS-Filtered Sell metrics.
# tlv, tpv, tfv:     Final System Totals for LVP, Partial Veto, Full Veto.
# i, j, k, n:         Iterators and array size variables.
# sorted_list[]:     Alphabetized list of symbols for the final table.
# ==========================================================================================

# Portable Timer Function
function get_ms() {
    return systime() 
}

BEGIN {  

    T_START = get_ms()
    INST_FILE = "instrument.txt"
    print "--- THROUGHPUT INSTRUMENTATION START ---" > INST_FILE

      FS = ","; OFS = "\t"  

      # Default values if not passed via command line
      if (!RS_DAYS) RS_DAYS = 5
      if (!ADD_PCT) ADD_PCT = 0.33
      if (!RL_CASH) RL_CASH = 50000
      if (!RL_DIP_PCT) RL_DIP_PCT = 1.0205
      if (!RL_STOP_PCT) RL_STOP_PCT = 0.95
      if (!RL_TARGET_PCT) RL_TARGET_PCT = 1.20
      if (!SMA_QUAL) SMA_QUAL = 0
      if (!RL_EXPANSION) RL_EXPANSION = 1.10
      if (!RL_ACC_MIN) RL_ACC_MIN = 8
      if (!RL_ACC_COUNT) RL_ACC_COUNT = 10
    if (!RUN_REPLAYS) RUN_REPLAYS = 0


      printf "# RL_CASH:" RL_CASH
      printf "\n# RL_DIP_PCT:" RL_DIP_PCT
      printf "\n# RL_STOP_PCT:" RL_STOP_PCT
      printf "\n# RL_TARGET_PCT:" RL_TARGET_PCT
      printf "\n# SMA_QUAL:" SMA_QUAL
      printf "\n# DEBUG_SYM:" DEBUG_SYM
      printf "\n# RL_EXPANSION:" RL_EXPANSION
      printf "\n# RL_ACC_MIN:" RL_ACC_MIN
      printf "\n# RL_ACC_COUNT:" RL_ACC_COUNT

      # Initialize Global RL Counters
      rl_wins = 0; rl_losses = 0; rl_sum_wins = 0; rl_sum_losses = 0
      rl_open_wins = 0; rl_open_losses = 0; rl_val_open_wins = 0; rl_val_open_losses = 0

    T_TRANSITION_START = get_ms()
}

# Currency-safe numeric conversion
function clean(v) {
      gsub(/[\$ \t,"]/, "", v)
      return v + 0
}

function to_iso(d) {
      gsub(/[\$ \t"]/, "", d); split(d, a, /[\/\-]/)
      # If the first segment is 4 digits, assume YYYY-MM-DD
      if (length(a[1]) == 4)  
            return sprintf("%04d%02d%02d", a[1], a[2], a[3])
      # Otherwise, fall back to the original MM/DD/YYYY logic
      return sprintf("%04d%02d%02d", a[3], a[1], a[2])
}
function abs(v) {  
      return v < 0 ? -v : v  
      }

# PHASE 1: HISTORY MAPPING (Truth Baseline)
ARGIND == 1 {
      if (FNR == 1) { T_P1 = get_ms() }
      if (FNR == 1) next #skips the first row since it is a header
      sym = toupper($3); #sym is getting set to the uppercase value of the stock symbol
      sorted_list[sym] = 1; #storing the symbol in the sorted array.  
      d_iso = to_iso($1); #d_iso is the date running through thte to_iso function which sets a universal format for all dates
       
      # the following two are running through clean to remove any dollar signs so awk can deal with a number and abs() so it is a positive number in case the history file has negatives for SELLs
      q = abs(clean($5)); #q is getting set to quantity.  
      p = abs(clean($6)); #p is getting set to price
     
      if (sym == "" || sym == "SYMBOL") next #this skips any blank lines or headers
       
      act_syms[sym] = 1; # This sets act_syms to 1 for the symbol
      h_rec_cnt++ # this increases the h_rec_cnt by one. this is used to simply show how many records were processed at the end.  

      if (inv_now[sym] == 0) #checking if current inventory count (inv_now) is zero before processing the record
      {  
            t_idx[sym]++; #Increasing the transaction index (t_idx) for the current symbol by 1
            tid = sym "_" t_idx[sym]; #Setting the transaction id (tid) to <symbol>_<transaction index>
            st_iso[tid] = d_iso; #setting the start date (st_iso) for the transaction to be date in history file
      }

      tid = sym "_" t_idx[sym]; #Setting transaction ID (tid) to <symbol>_<transaction index>.

      t_to_s[tid] = sym #t_to_s is a reverse lookup of the transaction id to get the symbol.  
       
      if (DEBUG_SYM != "" && sym == DEBUG_SYM)
            printf "\n\nsymbol:" sym "\ntid: " tid "\nq:" q "\np:" p "\ninv_now[sym]:" inv_now[sym] "\nd_iso:" d_iso "\nt_idx[sym]:" t_idx[sym] "\nst_iso[tid]:" st_iso[tid] "\nline:" $0;
       
      if ($4 == "Buy")  
      { #if the transaction in the history file is a BUY
            # Filtered Buy Replay: Store raw transactions
            hb_q[tid, ++hb_c[tid]] = q; hb_p[tid, hb_c[tid]] = p; hb_iso[tid, hb_c[tid]] = d_iso;

            # Tracker for ALL BUYs baseline
            total_bought_qty[tid] += q;
            total_bought_cost[tid] += (q * p);

            if (d_iso != st_iso[tid]) #if the date does not equal the start date of a transaction (i.e. this is a subsequent buy in an existing transaction.
            {  
                  b_cnt[tid]++; #Increase the buy count for the transaction by 1.
                  tb_q[tid, b_cnt[tid]] = q; #Set the tb_q tactical buy quantity for this transaction id and buy count to the quantity
                  tb_p[tid, b_cnt[tid]] = p #Set the tb_p tactical buy price for this transaction id and buy count to the price
            } else {
                  # Weighted Entry Logic for Entry Day
                  sum_entry_val[tid, d_iso] += (q * p);
                  sum_entry_qty[tid, d_iso] += q;

                  # Tracker for PURE B&H baseline (Initial day ONLY)
                  initial_entry_qty[tid] += q;
                  initial_entry_cost[tid] += (q * p);
            }

            m_pnl[tid] -= (q * p); #In a BUY, we decrease the PNL for this transaction.
            inv_now[sym] += q #since we are in a BUY, we increase the quantity of the current inventory

            # Targeted Logging for PnL BUYs
            if (DEBUG_SYM != "" && sym == DEBUG_SYM) printf DEBUG_SYM " DEBUG Phase1: %s BUY %d @ %.2f | New PnL: %.2f\n", d_iso, q, p, m_pnl[tid]  
      } else { #We are in a SELL
            # Filtered Strategy Replay: Store raw transactions
            hs_q[tid, ++hs_c[tid]] = q; hs_p[tid, hs_c[tid]] = p; hs_iso[tid, hs_c[tid]] = d_iso;

            if (inv_now[sym] - q > 0) #If the current inventory minus the amount sold in this transaction is greater than zero, then this is an interim SELL
            {  
                  s_cnt[tid]++; #Increase the sell count for the transaction by 1.
                  ts_q[tid, s_cnt[tid]] = q;  
                  ts_p[tid, s_cnt[tid]] = p  
                  ts_iso[tid, s_cnt[tid]] = d_iso #Store the date of the interim sell for TAC filtering
            }
            h_exact_sell_q[tid, d_iso] += q; #Set the h_exact_sell_q daily sell quantity
            h_exact_sell_p[tid, d_iso] = p #Set the h_exact_sell_p daily sell price

            m_pnl[tid] += (q * p); #In a SELL, we increase the PNL for this transaction.

            # Weighted Exit Logic (Handles Long positions hitting zero via a Sell)
            # This block triggers only on the transaction(s) that bring inventory to exactly zero.
            # Accumulates the total dollar value (Price * Quantity) of the closing trade(s).
          sum_exit_val[tid, d_iso] += (q * p);
            # Accumulates the total share quantity of the closing trade(s).
            sum_exit_qty[tid, d_iso] += q;

            inv_now[sym] -= q #since we are in a SELL, we decrease the quantity of the current inventory

            if (DEBUG_SYM != "" && sym == DEBUG_SYM)
                  printf "\n\nsymbol:" sym "\ntid: " tid "\ns_cnt[tid]:" s_cnt[tid] "\nq:" q "\np:" p "\nh_exact_sell_q[tid, d_iso]:" h_exact_sell_q[tid, d_iso] "\nh_exact_sell_p[tid, d_iso]:" h_exact_sell_p[tid, d_iso] "\nm_pnl[tid]:" m_pnl[tid] "\nsum_exit_val[tid, d_iso]:" sum_exit_val[tid, d_iso] "\nsum_exit_qty[tid, d_iso]:" sum_exit_qty[tid, d_iso] "\ninv_now[sym]:" inv_now[sym];

            # Targeted Logging for PnL SELLs
            if (DEBUG_SYM != "" && sym == DEBUG_SYM) printf DEBUG_SYM " DEBUG Phase1: %s SELL %d @ %.2f | New PnL: %.2f\n", d_iso, q, p, m_pnl[tid]  
      }

      h_exact_inv[tid, d_iso] = inv_now[sym] # We set the h_exact_inv Daily share balance for the transaction id and date
       
      if (inv_now[sym] == 0) #If the inventory is 0 after processing the record
      {  
            is_closed[tid] = 1; #We mark the transaction id as closed
          en_iso[tid] = d_iso; #We set the end date for the transation id as current date
            # Logic Fix: Calculates the VWAP for the terminal exit to resolve TAC deltas (Guard added for AXP crash)
            if (sum_exit_qty[tid, d_iso] > 0) hist_exit_p[tid] = sum_exit_val[tid, d_iso] / sum_exit_qty[tid, d_iso]
            else hist_exit_p[tid] = p
            # Logic Fix: Calculates the VWAP for the entry position (Guard added for AXP crash)
            if (sum_entry_qty[tid, st_iso[tid]] > 0) hist_entry_p[tid] = sum_entry_val[tid, st_iso[tid]] / sum_entry_qty[tid, st_iso[tid]]
            else hist_entry_p[tid] = p
             
            if (DEBUG_SYM != "" && sym == DEBUG_SYM)  
                  printf "\n\ntid:" tid "\nis_closed[tid]:" is_closed[tid] "\nen_iso[tid]:" en_iso[tid] "\nhist_exit_p[tid]:" hist_exit_p[tid] "\nhist_entry_p[tid]:" hist_entry_p[tid] "\n"
      }
}

# PHASE 4: ACCOUNTING PASS
function perform_audit(sym) {
       
      if (sym == "") return
    T_AUD_START = get_ms()
      acc_rec_cnt++; streak = 0; delete s_q; delete s_p; delete s_fv; last_tid = ""
      rl_inv = 0; rl_pnl = 0; rl_stop = 0; rl_target = 0
      s20 = s50 = s100 = s200 = 0 
    acc_rolling_hits = 0 # Optimized rolling counter for Acceptance

      for (j = 1; j <= d_ptr[sym]; j++) {
            iso = dates[sym, j]
            tid = ""
            for (id in st_iso) { if (t_to_s[id] == sym && iso >= st_iso[id] && (iso <= en_iso[id] || !en_iso[id])) tid = id }
             
            # Rocket Launcher Target Calculation (Updated Every Day to use Previous Day's SMA)
            if (DEBUG_SYM != "" && sym == DEBUG_SYM)  
                  printf "\n\nTarget Calc\nrl_target:" rl_target "\ndate:" iso "\nsma50[dates[sym, j-1]]:" sma50[dates[sym, j-1]]
            if (j > 1 && sma50[dates[sym, j-1]] > 0)  
                  {
                  rl_target = sma50[dates[sym, j-1]] * RL_TARGET_PCT
                  }

            # Optimized Sliding Window SMA Calculations
        p_today = raw_cl[sym, iso]
        s20 += p_today; if (j > 20) s20 -= raw_cl[sym, dates[sym, j-20]]
        if (j >= 20) sma20[iso] = s20 / 20
        
        s50 += p_today; if (j > 50) s50 -= raw_cl[sym, dates[sym, j-50]]
        if (j >= 50) sma50[iso] = s50 / 50
        
        s100 += p_today; if (j > 100) s100 -= raw_cl[sym, dates[sym, j-100]]
        if (j >= 100) sma100[iso] = s100 / 100
        
        s200 += p_today; if (j > 200) s200 -= raw_cl[sym, dates[sym, j-200]]
        if (j >= 200) sma200[iso] = s200 / 200

        # Optimized Rolling Acceptance Qualifier
        p_idx = j; prev_p_iso = dates[sym, p_idx-1]
        if (sma50[prev_p_iso] > 0 && raw_cl[sym, iso] > sma50[prev_p_iso]) acc_rolling_hits++
        if (j > RL_ACC_COUNT) {
            old_idx = j - RL_ACC_COUNT; old_iso = dates[sym, old_idx]; old_prev_idx = old_idx - 1; old_prev_iso = dates[sym, old_prev_idx]
            if (sma50[old_prev_iso] > 0 && raw_cl[sym, old_iso] > sma50[old_prev_iso]) acc_rolling_hits--
        }
        acceptance = (acc_rolling_hits >= RL_ACC_MIN) ? 1 : 0

            y_iso = dates[sym, j-1];  
            y_sma = sma50[y_iso]
            if (DEBUG_SYM != "" && sym == DEBUG_SYM)  
                  printf "\n\nCHECK Launch pad. IS raw low within the SMA\nSymbol:" sym "\ndate:" iso "\ny_iso:" y_iso "\nraw_lo[sym, iso]:" raw_lo[sym, iso] "\ny_sma:" y_sma "\nSMA_QUAL:" SMA_QUAL "\nRL_DIP_PCT:" RL_DIP_PCT "\nraw_cl[sym, iso]:" raw_cl[sym, iso] "\nraw_op[sym, iso]:" raw_op[sym, iso] "\nrl_inv:" rl_inv
            if (DEBUG_SYM != "" && sym == DEBUG_SYM)  
                  printf "\n\nSMA checks:date:" iso "\nsma20[iso]" sma20[iso] "\nsma50[iso]:" sma50[iso] "\nsma100[iso]:" sma100[iso] "\nsma200[iso]:" sma200[iso]

            # Rocket Launcher Strategy Pass
            if (rl_inv > 0) {
                  # if (DEBUG_SYM != "" && sym == DEBUG_SYM)  
                  # printf "\n\nDuring position\nraw_lo[sym, iso]:" raw_lo[sym, iso] "\nrl_stop:" rl_stop "\nraw_hi[sym, iso]:" raw_hi[sym, iso] "\nrl_target:" rl_target "\ndate:" iso  

                  if (raw_lo[sym, iso] <= rl_stop || raw_hi[sym, iso] >= rl_target)  
                  {
                        if (rl_target > raw_op[sym, iso])
                              rl_sell = rl_target
                        else
                              rl_sell = raw_op[sym, iso]
                        if (raw_lo[sym, iso] <= rl_stop)
                              rl_sell = rl_stop

                        # Calc trade outcome for summary
                        trade_pnl = (rl_inv * rl_sell) - RL_CASH
                        if (trade_pnl > 0)  
                        {  
                              rl_wins++;  
                              rl_sum_wins += trade_pnl  
                        }
                        else  
                        {  
                              rl_losses++;  
                              rl_sum_losses += trade_pnl  
                        }

                        # Track realized PnL per date for running tally
                        daily_realized_pnl[iso] += trade_pnl

                        # Surgical Addition: Track Closed Trades List with chronological pointer lookup for SMA
                        rl_closed_list[++rl_closed_ptr] = sprintf("%-8s | %-12s | %-12.2f | %-8.4f  | %-8.4f | %-12s | %-13.2f | %-8.2f", sym, rl_entry_iso[sym], rl_entry_p[sym], (sma50[dates[sym, rl_entry_idx[sym]-1]] > 0 ? (rl_entry_p[sym]-sma50[dates[sym, rl_entry_idx[sym]-1]])/sma50[dates[sym, rl_entry_idx[sym]-1]] : 0), (rl_stop > 0 ? (rl_entry_p[sym]-rl_stop)/rl_stop: 0), iso, rl_sell, (trade_pnl/RL_CASH)*100)
                        				
                        rl_pnl += (rl_inv * rl_sell); rl_inv = 0

                        rl_pnl -= RL_CASH

                        rocket_pnl[sym] = rl_pnl + (rl_inv * rl_sell)

                        if (DEBUG_SYM != "" && sym == DEBUG_SYM)  
                              printf "\n\nClosing position at(rl_inv * raw_cl[sym, iso]):" rl_inv * raw_cl[sym, iso] "\nraw_lo[sym, iso]:" raw_lo[sym, iso] "\nrl_stop:" rl_stop "\nraw_hi[sym, iso]:" raw_hi[sym, iso] "\nrl_target:" rl_target "\ndate:" iso "\nTotal now:" rl_pnl +   (rl_inv * rl_sell) "\nrl_sell:" rl_sell

                  }
            } else if (j > 53 && sma50[dates[sym, j]] > sma50[dates[sym, j-3]]) {
                  if (DEBUG_SYM != "" && sym == DEBUG_SYM)  
                        printf "\n\nSMA Compare. SMA IS greater than SMA of 3 days ago\nSymbol:" sym "\ndate:" iso "\nsma50[dates[sym, j-1]]:" sma50[dates[sym, j-1]] "\nsma50[dates[sym, j-4]]:" sma50[dates[sym, j-4]]


                  if (raw_lo[sym, iso] < (y_sma * RL_DIP_PCT) && (raw_lo[sym, iso] > y_sma * (1-(RL_DIP_PCT-1))) && raw_cl[sym, iso] > raw_op[sym, iso] && raw_cl[sym, iso] > y_sma && sma200[y_iso] > 0 && (sma20[iso] > sma50[iso] && sma50[iso] > sma100[iso] && sma100[iso] > sma200[iso]))  
                  {
                        # SMA Stack Qualifier Logic
                        if (SMA_QUAL == 1) {
                              if (DEBUG_SYM != "" && sym == DEBUG_SYM)  
                                    printf "\n\nSMA checks:date:" iso "\nsma20[iso]" sma20[iso] "\nsma50[iso]:" sma50[iso] "\nsma100[iso]:" sma100[iso] "\nsma200[iso]:" sma200[iso]
#                              if (!(sma20[iso] > sma50[iso] && sma50[iso] > sma100[iso] && sma100[iso] > sma200[iso])) continue
                        }

                        # Expansion Flag Calculation (at least one close >= Expansion threshold in last 10 days)
                        expansion = 0
                        for (k=0; k < 10; k++) {
                              p_idx = j - k; if (p_idx < 2) continue
                              p_iso = dates[sym, p_idx]; prev_p_idx = p_idx - 1; prev_p_iso = dates[sym, prev_p_idx]
                              if (sma50[prev_p_iso] > 0 && raw_cl[sym, p_iso] >= (sma50[prev_p_iso] * RL_EXPANSION)) { expansion = 1; break }
                        }

                        # Composite Trade Entry Condition
                        if (expansion && acceptance) {

					if (DEBUG_SYM != "" && sym == DEBUG_SYM)  
						printf "\n\nLaunch pad. expansion and acceptance verified\nSymbol:" sym "\ndate:" iso "\ny_iso:" y_iso "\nraw_lo[sym, y_iso]:" raw_lo[sym, y_iso] "\ny_sma:" y_sma "\nRL_DIP_PCT:" RL_DIP_PCT "\nraw_cl[sym, y_iso]:" raw_cl[sym, y_iso] "\nraw_op[sym, y_iso]:" raw_op[sym, y_iso]  

					# Technical Fix: Division by zero guard for corrupted data/headers
					next_day_iso = dates[sym, j+1]
					if (raw_op[sym, next_day_iso] > 0)  
					{

						rl_inv = RL_CASH / raw_op[sym, next_day_iso]
						rl_stop = raw_lo[sym, iso] * RL_STOP_PCT
						rl_entry_iso[sym] = next_day_iso; rl_entry_p[sym] = raw_op[sym, next_day_iso]
						# Surgical Addition: Store chronological entry index to calculate days open
						rl_entry_idx[sym] = j+1
						if (DEBUG_SYM != "" && sym == DEBUG_SYM)  
							printf "\n\nSetting Values\nSymbol:" sym "\ndate:" iso "\nrl_inv:" rl_inv "\nrl_pnl:" rl_pnl "\nrl_stop:" rl_stop "\nrl_target:" rl_target "\nBuy Price next day open:" raw_op[sym, next_day_iso]

					}
				}
                  }
            }

            # Track daily position count and tickers
            if (rl_inv > 0) {
                  daily_active_count[iso]++
                  daily_tickers[iso] = daily_tickers[iso] sym " "
            }
            all_trading_dates[iso] = 1

            if (tid == "") { if (streak) tid = last_tid; else continue }
            last_tid = tid
             
            crs = 0; cur_spy_idx = spy_idx[iso]
            # RS calculation logic utilizing command-line RS_DAYS
            if (j > RS_DAYS && cur_spy_idx > RS_DAYS) {
                  old_iso = dates[sym, j-RS_DAYS]; old_spy_iso = spy_s[cur_spy_idx-RS_DAYS]
                  if (raw_cl[sym, old_iso] > 0 && spy_p[old_spy_iso] > 0) {
                        ticker_ret = (raw_cl[sym, iso] - raw_cl[sym, old_iso]) / raw_cl[sym, old_iso]
                        spy_ret = (spy_p[iso] - spy_p[old_spy_iso]) / spy_p[old_spy_iso]
                        if (ticker_ret > spy_ret) crs = 1
                  }
            }
            # Populate history for the filtered replay metrics
            hist_rs[sym, iso] = crs

            cq = h_exact_sell_q[tid, iso]
             
            if (DEBUG_SYM != "" && sym == DEBUG_SYM) trace[sym] = trace[sym] sprintf("\n[%s]: Sell=%d | RS=%d | Streak=%d | Inv=%d", iso, cq, crs, streak, h_exact_inv[tid, iso])
             
            if (streak && (!crs || j == d_ptr[sym])) {
                  next_iso = dates[sym, j+1]
                  exit_p = (next_iso != "") ? raw_op[sym, next_iso] : raw_cl[sym, iso]
                  if (DEBUG_SYM != "" && sym == DEBUG_SYM) trace[sym] = trace[sym] sprintf(" -> ACTION: EXIT AT %.2f", exit_p)
                  for (v_iso in s_q) {
                        imp = (s_p[v_iso] - exit_p) * s_q[v_iso]
                        if (s_fv[v_iso]) { fv_ledger[tid] += imp; term_anchor[tid] = exit_p }
                        else { pv_ledger[tid] += imp }
                        diag[sym] = diag[sym] "\n" v_iso ": " (s_fv[v_iso]?"FULL VETO":"PARTIAL VETO") " | Math: (" s_p[v_iso] " - " exit_p ") * " s_q[v_iso] " = " imp
                  }
                  streak = 0; delete s_q; delete s_p; delete s_fv
            }
            if (cq > 0 && crs) {
                  streak = 1; s_q[iso] = cq; s_p[iso] = h_exact_sell_p[tid, iso]
                  if (h_exact_inv[tid, iso] == 0) s_fv[iso] = 1
                  if (DEBUG_SYM != "" && sym == DEBUG_SYM) trace[sym] = trace[sym] " -> VETO CAPTURED"
            }
      }

      # Tracking Open Trades at end of Symbol audit
      if (rl_inv > 0) {
            last_cl = raw_cl[sym, dates[sym, d_ptr[sym]]]
            _open_pnl = (rl_inv * last_cl) - RL_CASH
            if (_open_pnl > 0) {
                  rl_open_wins++; rl_val_open_wins += _open_pnl
            } else {
                  rl_open_losses++; rl_val_open_losses += _open_pnl
            }
            # Surgical Addition: Append # days open to the string
            rl_open_list[++rl_open_ptr] = sprintf("%-8s | %-12s | %-12.2f | %-13.2f | %-8.2f | %-10d", sym, rl_entry_iso[sym], rl_entry_p[sym], last_cl, (_open_pnl/RL_CASH)*100, (d_ptr[sym] - rl_entry_idx[sym]))
      }

    # Gated Block for heavy Replay and Ledger math
    if (RUN_REPLAYS == 1) {
          # NEW: LVP LEDGER ACCOUNTING (Based on programmatic entry targets)
          for (id in st_iso) {
                if (t_to_s[id] == sym && is_closed[id]) {
                      anchor_p = hist_entry_p[id]
                      for (k = 1; k <= b_cnt[id]; k++) {
                            # Target price is initial entry * (1 + ADD_PCT)
                            prog_p = anchor_p * (1 + ADD_PCT)
                            lvp_imp = (prog_p - tb_p[id, k]) * tb_q[id, k]
                            lvp_ledger[id] += lvp_imp
                            diag[sym] = diag[sym] "\n" id " LVP: (" prog_p " - " tb_p[id, k] ") * " tb_q[id, k] " = " lvp_imp
                      }
                }
          }

          # REPLAY PASS: Calculate Filtered Strategy Metrics
          for (id in st_iso)  
          {
                if (t_to_s[id] != sym || !is_closed[id]) continue
                 
                # RS BUY Replay (Additions filtered by yesterday's RS)
                inv_rb = 0; pnl_rb = 0
                for (k = 1; k <= hb_c[id]; k++) {
                      if (hb_iso[id, k] == st_iso[id]) { pnl_rb -= (hb_q[id, k] * hb_p[id, k]); inv_rb += hb_q[id, k] }
                      else {
                            idx = iso_idx[sym, hb_iso[id, k]]; prev_trading_iso = dates[sym, idx-1]
                            if (hist_rs[sym, prev_trading_iso]) { pnl_rb -= (hb_q[id, k] * hb_p[id, k]); inv_rb += hb_q[id, k] }
                      }
                }
                if (inv_rb > 0) pnl_rb += (inv_rb * hist_exit_p[id])
                rs_buy_val[id] = pnl_rb

                # RS SELL Replay (Initial Entry Only + Interim Sells only if yesterday failed RS)
                inv_rs = 0; pnl_rs = 0
                for (k = 1; k <= hb_c[id]; k++) {
                      # Requirement Change: Only include Initial Entry day buys for the RS SELL baseline
                      if (hb_iso[id, k] == st_iso[id]) { pnl_rs -= (hb_q[id, k] * hb_p[id, k]); inv_rs += hb_q[id, k] }
                }
                for (k = 1; k <= hs_c[id]; k++) {
                      if (inv_rs <= 0) break
                      s_iso = hs_iso[id, k]; idx = iso_idx[sym, s_iso]
                      # Strategy: Sells executed if yesterday failed RS OR if it is the Final Exit Day
                      if (s_iso == en_iso[id] || !hist_rs[sym, dates[sym, idx-1]]) {
                            sq = (hs_q[id, k] > inv_rs) ? inv_rs : hs_q[id, k]
                            pnl_rs += (sq * hs_p[id, k]); inv_rs -= sq
                      }
                }
                if (inv_rs > 0) pnl_rs += (inv_rs * hist_exit_p[id])
                rs_sell_val[id] = pnl_rs
          }
    }

      # Memory Release Pass (Surgical: clear heavy historical prices for this sym)
      for (k=1; k <= d_ptr[sym]; k++) {
            _d = dates[sym, k]
            delete raw_op[sym, _d]; delete raw_hi[sym, _d]; delete raw_lo[sym, _d]; delete raw_cl[sym, _d]
      }
    printf "Audit Symbol [%s] processed %d days in %ds\n", sym, d_ptr[sym], (get_ms()-T_AUD_START) >> INST_FILE
    T_TRANSITION_START = get_ms()
}

FILENAME ~ /SPY\.csv/ { if (FNR < 4) next; iso = to_iso($1); spy_p[iso] = clean($5); spy_rec_cnt++; spy_idx[iso] = spy_rec_cnt; spy_s[spy_rec_cnt] = iso; next }

{
      if (FILENAME == h_file || FILENAME ~ /SPY\.csv|look\.csv|History/) {
        if (FILENAME == h_file && FNR == 1) { T_P1 = get_ms() }
        next
    }
      if (FILENAME != prev_file) {  
        if (prev_file != "" && prev_file != h_file && prev_file !~ /SPY\.csv/) {
            printf "Transition from [%s]: Lines read=%d | Time=%ds\n", prev_file, FNR, (get_ms()-T_TRANSITION_START) >> INST_FILE
        }
            perform_audit(cur_s);  
            prev_file = FILENAME
        T_TRANSITION_START = get_ms()
            fn = toupper(FILENAME);  
            sub(/.*\//, "", fn);  
            sub(/.*\\/, "", fn);  
            sub(/\.CSV$/, "", fn)
            r1 = toupper($1);  
            cur_s = (act_syms[fn]) ? fn : ((act_syms[r1]) ? r1 : "")
            }
      if (FNR == 2 && cur_s == "") {  
            r2 = toupper($1);  
            if (act_syms[r2])  
                  cur_s = r2  
            }
      # Technical Fix: Added price numeric check to skip non-standard headers (BYD crash fix)
      if (cur_s == "" || $1 == "" || $1 ~ /[a-zA-Z]/ || clean($2) == 0) next
      iso = to_iso($1);  
      op = clean($6);  
      hi = clean($4);  
      lo = clean($5);  
      cl = clean($3);  
      raw_op[cur_s, iso] = op;  
      raw_hi[cur_s, iso] = hi;  
      raw_lo[cur_s, iso] = lo;  
      raw_cl[cur_s, iso] = cl;  
      scout_rec_cnt++
      for (id in en_iso)  
      {  
            if (t_to_s[id] == cur_s && en_iso[id] == iso)  
                  term_anchor[id] = cl  
      }
      if (!seen[cur_s, iso]++)  
      {
            dates[cur_s, ++d_ptr[cur_s]] = iso
            iso_idx[cur_s, iso] = d_ptr[cur_s]
      }
}

END {

    T_END_START = get_ms()
      perform_audit(cur_s)
      if (DEBUG_SYM != "") print trace[DEBUG_SYM]
       
      #print "\n========================================================================================================================================================================================================================"
      #printf "%-8s | %-12s | %-12s | %-12s | %-12s | %-12s | %-12s | %-12s | %-10s | %-10s | %-10s | %-10s | %-10s\n", "SYMBOL", "MY SYS PNL", "PURE B&H", "ALL BUY B&H", "RS BUY PNL", "RS SELL PNL", "TAC BUY VAL", "TAC SELL VAL", "LVP VAL", "PART VETO", "FULL VETO", "TOT ALPHA", "ROCKET L"
      printf "%-8s | %-10s\n", "SYMBOL", "ROCKET L" > "RL_Summary.csv"
      #print "------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
      n = asorti(act_syms, sorted_list)
      for (i = 1; i <= n; i++) {
            s = sorted_list[i]; sp=vb=vs=lv=pv=fv=spbh=sabh=srsb=srss=0
            for (id in t_to_s) { if (t_to_s[id] == s && is_closed[id]) {  
                  anchor = hist_exit_p[id]
                  spbh += (anchor * initial_entry_qty[id]) - initial_entry_cost[id]
                  sabh += (anchor * total_bought_qty[id]) - total_bought_cost[id]
                  srsb += rs_buy_val[id]; srss += rs_sell_val[id]
                  sp += m_pnl[id]; lv += lvp_ledger[id]; pv += pv_ledger[id]; fv += fv_ledger[id]
                  for(k=1; k<=b_cnt[id]; k++) { vb += (anchor - tb_p[id,k]) * tb_q[id,k] }
                  for(k=1; k<=s_cnt[id]; k++) {  
                        if (ts_iso[id, k] != en_iso[id]) {  
                              vs += (ts_p[id,k] - anchor) * ts_q[id,k]
                        }
                  }
            }}
            if (sp != 0 || rocket_pnl[s] != 0)  
      {
#                  printf "%-8s | %12.2f | %12.2f | %12.2f | %12.2f | %12.2f | %12.2f | %12.2f | %10.2f | %10.2f | %10.2f | %10.2f | %10.2f\n", s, sp, spbh, sabh, srsb, srss, vb, vs, lv, pv, fv, (lv+pv+fv), rocket_pnl[s]
                  printf "%-8s | %10.2f\n", s, rocket_pnl[s] >> "RL_Summary.csv"
                  tm += sp; trl += rocket_pnl[s]
            }
      }
      print "------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
#      printf "%-8s | %12.2f | %12.2f | %12.2f | %12.2f | %12.2f | %12.2f | %12.2f | %10.2f | %10.2f | %10.2f | %10.2f | %10.2f\n", "TOTAL", tm, tpbh, tabh, trsb, trss, tvb, tvs, tlv, tpv, tfv, (tlv+tpv+tfv), trl
      printf "%-8s | %10.2f\n", "TOTAL", trl

#      printf "RL_CASH,SMA_QUAL,RL_DIP_PCT,RL_STOP_PCT,RL_TARGET_PCT,TOTAL PNL,# wins,#losses,% wins, %losses,win loss ratio,AVG wins,AVG losses,AVG PNL/trade,# open wins, $ open wins, avg open winners, # open losses, $ open losses, avg open losers" >> "RocketLauncher.csv"
      printf "\n" RL_CASH "," SMA_QUAL "," RL_DIP_PCT "," RL_STOP_PCT "," RL_TARGET_PCT "," trl "," rl_wins "," rl_losses "," (rl_wins > 0 ? rl_wins / (rl_wins+rl_losses) : 0) "," (rl_wins > 0 ? rl_losses / (rl_wins+rl_losses) : 0) "," rl_sum_wins/-rl_sum_losses "," (rl_wins > 0 ? rl_sum_wins / rl_wins : 0) "," (rl_losses > 0 ? rl_sum_losses / rl_losses : 0) "," (rl_wins+rl_losses > 0 ? trl/(rl_wins+rl_losses) : 0) "," rl_open_wins "," rl_val_open_wins "," (rl_open_wins > 0 ? rl_val_open_wins/rl_open_wins : 0) "," rl_open_losses "," rl_val_open_losses "," (rl_open_losses > 0 ? rl_val_open_losses/rl_open_losses : 0) >> "RocketLauncher.csv"
      # Specific List of Open Rocket Launcher Positions
      if (rl_open_ptr > 0) {
            #print "\nSPECIFIC OPEN ROCKET LAUNCHER POSITIONS"
            #print "--------------------------------------------------------------------------------------"
            printf "%-8s | %-12s | %-12s | %-13s | %-8s | %-10s\n", "SYMBOL", "DATE OPENED", "ENTRY PRICE", "CURRENT PRICE", "PNL %", "# DAYS OPEN" > "RL_Open.csv"
            #print "--------------------------------------------------------------------------------------"
            for (xp=1; xp<=rl_open_ptr; xp++) print rl_open_list[xp] >> "RL_Open.csv"
      }

      # Specific List of Closed Rocket Launcher Positions
      if (rl_closed_ptr > 0) {
            #print "\nALL CLOSED ROCKET LAUNCHER POSITIONS"
            #print "--------------------------------------------------------------------------"
            printf "%-8s | %-12s | %-12s | %-12s | %-13s | %-8s\n", "SYMBOL", "DATE OPENED", "ENTRY PRICE", "R&R THRESHOLD", "RISK (% to stop)", "DATE CLOSED", "EXIT PRICE", "PNL %" > "RL_Closed.csv"
            #print "--------------------------------------------------------------------------"
            for (xc=1; xc<=rl_closed_ptr; xc++) print rl_closed_list[xc] >> "RL_Closed.csv"
      }

      # DAILY PORTFOLIO TRACKER WITH TICKER LIST
      print "\nDAILY ROCKET LAUNCHER EXPOSURE & REALIZED PNL"
      print "--------------------------------------------------------------------------------------------------------------------------"
      printf "%-12s | %-14s | %-18s | %-40s\n", "DATE", "ACTIVE POS", "REALIZED PNL (CUM)", "SYMBOLS IN PORTFOLIO"
      print "--------------------------------------------------------------------------------------------------------------------------"
      m_realized = 0
      k_dates = asorti(all_trading_dates, sorted_dates)
      for (idx=1; idx<=k_dates; idx++) {
            d_iso = sorted_dates[idx]
            m_realized += daily_realized_pnl[d_iso]
            printf "%-12s | %-14d | %18.2f | %-40s\n", d_iso, daily_active_count[d_iso], m_realized, daily_tickers[d_iso]
      }

    printf "--- TOTAL RUNTIME: %ds ---\n", (get_ms()-T_START) >> INST_FILE

#      print "\n--- FORENSIC MATH LOG ---"
#      for (i = 1; i <= n; i++) { s = sorted_list[i]; if (diag[s] != "") print "SYMBOL: " s diag[s] "\n-----------------------------------------------------------" }
#      for (i = 1; i <= n; i++) { s = sorted_
