import argparse
import os
from datetime import datetime, timedelta

import pandas as pd
import yfinance as yf

try:
    import duckdb
except ImportError:
    duckdb = None

try:
    from ohlcv_store import prune_orphan_symbols as _prune_orphan_symbols
except ImportError:
    try:
        from stock_analysis.ohlcv_store import prune_orphan_symbols as _prune_orphan_symbols
    except ImportError:
        _prune_orphan_symbols = None

# --- CONFIGURATION ---
DATA_DIR = "C:\\Users\\songg\\Downloads\\stockresearch\\data\\newdata\\data"
# Start date for full-history downloads and automatic backfill detection.
START_DATE = "2010-01-01"

# End date is today+1 so yfinance includes latest close
END_DATE = (datetime.now() + timedelta(days=1)).strftime("%Y-%m-%d")
DEFAULT_DB_PATH = "C:\\Users\\songg\\Downloads\\stockresearch\\data\\ohlcv.duckdb"
DEFAULT_DB_TABLE = "prices"
DEFAULT_MODE = "incremental"
DEFAULT_INCREMENTAL_DAYS = 7
# One-time safety backfill (kept explicit so symbol gets full history even if a short file exists).
FORCE_FULL_BACKFILL_SYMBOLS = {"P"}

# Replace this list with your full set of tickers
# Based on your directory, I've initialized the first few:
TICKERS = [
    "A",
    "AA",
    "AAL",
    "AAMI",
    "AAON",
    "AAP",
    "AAT",
    "ABBNY",
    "ABBV",
    "ABCB",
    "ABG",
    "ABM",
    "ABNB",
    "ABR",
    "ABT",
    "ABUS",
    "ACA",
    "ACAD",
    "ACLS",
    "ACM",
    "ACN",
    "ACRS",
    "ACU",
    "ADBE",
    "ADI",
    "ADMA",
    "ADM",
    "ADNT",
    "ADP",
    "ADPT",
    "ADSK",
    "AEG",
    "AEHR",
    "AEIS",
    "AEM",
    "AEO",
    "AER",
    "AFG",
    "AFL",
    "AGI",
    "AGM",
    "AGNC",
    "AGO",
    "AGX",
    "AGYS",
    "AHCO",
    "AHT",
    "AI",
    "AIG",
    "AIR",
    "AIT",
    "AIZ",
    "AJG",
    "AKAM",
    "AKR",
    "AKTS",
    "AL",
    "ALB",
    "ALBY",
    "ALDX",
    "ALEC",
    "ALFVY",
    "ALG",
    "ALGM",
    "ALGN",
    "ALL",
    "ALLE",
    "ALNY",
    "ALNT",
    "ALSN",
    "AMAT",
    "AMCR",
    "AMD",
    "AME",
    "AMG",
    "AMGN",
    "AMH",
    "AMKR",
    "AMN",
    "AMP",
    "AMRC",
    "AMRZ",
    "AMT",
    "AMTX",
    "AMWD",
    "AMWL",
    "AMZN",
    "AN",
    "ANAB",
    "ANDE",
    "ANET",
    "ANF",
    "ANGO",
    "ANIK",
    "ANIP",
    "ANNX",
    "AON",
    "AOS",
    "AOSL",
    "AOUT",
    "APA",
    "APAM",
    "APD",
    "APG",
    "APH",
    "APLD",
    "APPS",
    "APTV",
    "APYX",
    "ARE",
    "ARES",
    "ARIS",
    "ARW",
    "ASH",
    "ASM",
    "ASMIY",
    "ASML",
    "ATEN",
    "ATEYY",
    "ATI",
    "ATLC",
    "ATO",
    "ATR",
    "ATUSF",
    "AU",
    "AUGO",
    "AVA",
    "AVAV",
    "AVGO",
    "AVY",
    "AWK",
    "AWI",
    "AX",
    "AXP",
    "AXSM",
    "AYI",
    "AZO",
    "B",
    "BA",
    "BAC",
    "BAESY",
    "BALL",
    "BANC",
    "BANF",
    "BAP",
    "BAX",
    "BBIO",
    "BBVA",
    "BBW",
    "BC",
    "BCH",
    "BDGIF",
    "BDX",
    "BELFA",
    "BELFB",
    "BEN",
    "BEP",
    "BFC",
    "BIIB",
    "BIO",
    "BK",
    "BKHYY",
    "BKNG",
    "BKR",
    "BKTI",
    "BKV",
    "BLBD",
    "BLD",
    "BLHK",
    "BLK",
    "BLX",
    "BMRN",
    "BMY",
    "BN",
    "BPOP",
    "BR",
    "BRK.B",
    "BRO",
    "BSX",
    "BURL",
    "BVN",
    "BWA",
    "BWLP",
    "BWXT",
    "BX",
    "BXMT",
    "BXP",
    "BYD",
    "C",
    "CACI",
    "CAMT",
    "CASH",
    "CASY",
    "CAT",
    "CBRE",
    "CBOE",
    "CCBG",
    "CCJ",
    "CDE",
    "CDNS",
    "CDW",
    "CE",
    "CECO",
    "CELH",
    "CENX",
    "CF",
    "CFG",
    "CGC",
    "CHCI",
    "CHDN",
    "CHEF",
    "CHRW",
    "CHTR",
    "CHYM",
    "CI",
    "CIB",
    "CIEN",
    "CINF",
    "CL",
    "CLF",
    "CLS",
    "CLX",
    "CM",
    "CMC",
    "CMCL",
    "CME",
    "CMG",
    "CMI",
    "CMS",
    "CNC",
    "CNM",
    "CNO",
    "CNP",
    "CNQ",
    "CNQ",
    "CNX",
    "COF",
    "COHR",
    "COKE",
    "COO",
    "COP",
    "COR",
    "CPA",
    "CPB",
    "CPRT",
    "CPT",
    "CRH",
    "CRL",
    "CRM",
    "CRS",
    "CRUS",
    "CRZBY",
    "CSCO",
    "CSGP",
    "CSTM",
    "CSX",
    "CTAS",
    "CTRE",
    "CTS",
    "CTSH",
    "CTVA",
    "CVCO",
    "CVX",
    "CW",
    "CWCO",
    "CWK",
    "CXDO",
    "CYD",
    "CYTK",
    "CZR",
    "D",
    "DAL",
    "DBSDY",
    "DCO",
    "DD",
    "DDS",
    "DE",
    "DECK",
    "DG",
    "DGII",
    "DHI",
    "DHR",
    "DHT",
    "DIS",
    "DKL",
    "DLTR",
    "DNBBY",
    "DOCN",
    "DOV",
    "DRD",
    "DRI",
    "DRS",
    "DSGX",
    "DTE",
    "DUK",
    "DVA",
    "DVN",
    "DXC",
    "DXCM",
    "DXPE",
    "DY",
    "EA",
    "EADSY",
    "EAT",
    "EBAY",
    "EBKDY",
    "EC",
    "ECL",
    "ECVT",
    "ED",
    "EDVMF",
    "EFX",
    "EGO",
    "EGP",
    "EHC",
    "EIX",
    "EL",
    "EME",
    "EMN",
    "EMR",
    "ENPH",
    "ENS",
    "ENSG",
    "ENVA",
    "EOG",
    "EQIX",
    "EQR",
    "ES",
    "ESEA",
    "ESE",
    "ESLT",
    "ESOA",
    "ESP",
    "ESS",
    "ETN",
    "ETR",
    "EVR",
    "EVRG",
    "EW",
    "EXC",
    "EXEL",
    "EXLS",
    "EXPD",
    "EXPE",
    "EXR",
    "EXTR",
    "EZPW",
    "F",
    "FANG",
    "FAST",
    "FBAK",
    "FBIN",
    "FBP",
    "FCFS",
    "FCX",
    "FDS",
    "FE",
    "FEDU",
    "FEIM",
    "FERG",
    "FHB",
    "FHI",
    "FFIV",
    "FINMY",
    "FIS",
    "FISV",
    "FITB",
    "FIX",
    "FLG",
    "FLEX",
    "FMC",
    "FMX",
    "FN",
    "FNF",
    "FNV",
    "FOXA",
    "FRBA",
    "FRD",
    "FRO",
    "FRT",
    "FSI",
    "FTAI",
    "FTNT",
    "FTRE",
    "FTV",
    "FUNC",
    "GD",
    "GCT",
    "GDDY",
    "GE",
    "GEV",
    "GFI",
    "GH",
    "GHM",
    "GILD",
    "GIS",
    "GL",
    "GLW",
    "GM",
    "GMAB",
    "GOOG",
    "GOOGL",
    "GPC",
    "GPN",
    "GRAL",
    "GRMN",
    "GS",
    "GSHD",
    "GTX",
    "GVA",
    "GWW",
    "HALO",
    "HAS",
    "HBAN",
    "HBM",
    "HCA",
    "HCI",
    "HD",
    "HDLMY",
    "HG",
    "HGV",
    "HIG",
    "HII",
    "HL",
    "HLI",
    "HLT",
    "HMY",
    "HOLX",
    "HRL",
    "HROW",
    "HSBC",
    "HST",
    "HSY",
    "HTHIY",
    "HUBB",
    "HUM",
    "HUN",
    "HWBK",
    "HWKN",
    "HWM",
    "IBKR",
    "IBP",
    "ICE",
    "IDCC",
    "IDR",
    "IDXX",
    "IESC",
    "IEX",
    "IFF",
    "IIIN",
    "IMVT",
    "INCY",
    "INFY",
    "ING",
    "INOD",
    "INSM",
    "INTC",
    "INTU",
    "IP",
    "IPAR",
    "IQV",
    "IR",
    "IRM",
    "IRMD",
    "ISNPY",
    "ISRG",
    "ITIC",
    "ITRN",
    "ITT",
    "ITW",
    "IVZ",
    "JBL",
    "JBHT",
    "JCI",
    "JKHY",
    "JMIA",
    "JNJ",
    "JOE",
    "JPM",
    "KAJMY",
    "KB",
    "KBCSY",
    "KEY",
    "KEYS",
    "KGC",
    "KIM",
    "KINS",
    "KLAC",
    "KMB",
    "KMI",
    "KMX",
    "KO",
    "KR",
    "KSS",
    "KTOS",
    "L",
    "LAUR",
    "LDOS",
    "LEA",
    "LECO",
    "LEN",
    "LET",
    "LEU",
    "LH",
    "LHX",
    "LII",
    "LIN",
    "LINC",
    "LITE",
    "LLY",
    "LMAT",
    "LMB",
    "LMT",
    "LMND",
    "LNC",
    "LNT",
    "LOPE",
    "LOW",
    "LPG",
    "LRCX",
    "LSCC",
    "LUGDF",
    "LUMN",
    "LUV",
    "LVS",
    "LW",
    "LYB",
    "LYV",
    "MA",
    "MAKO",
    "MAR",
    "MARUY",
    "MAS",
    "MAT",
    "MATX",
    "MC",
    "MCD",
    "MCK",
    "MCO",
    "MCRI",
    "MDGL",
    "MDT",
    "MDLZ",
    "MELI",
    "META",
    "MFC",
    "MGA",
    "MGM",
    "MHK",
    "MITSY",
    "MKC",
    "MLI",
    "MLM",
    "MMM",
    "MOD",
    "MNST",
    "MOS",
    "MPC",
    "MPWR",
    "MRK",
    "MRVL",
    "MS",
    "MSFT",
    "MT",
    "MTB",
    "MTD",
    "MTG",
    "MTSI",
    "MTX",
    "MTZ",
    "MU",
    "MWA",
    "MYRG",
    "NBHC",
    "NDAQ",
    "NEE",
    "NEM",
    "NFLX",
    "NG",
    "NGL",
    "NGVC",
    "NHC",
    "NIC",
    "NKE",
    "NMIH",
    "NNI",
    "NOC",
    "NOW",
    "NPO",
    "NRG",
    "NTRA",
    "NUE",
    "NVDA",
    "NVMI",
    "NWPX",
    "NXPI",
    "NXST",
    "NXT",
    "OCANF",
    "ODC",
    "ODFL",
    "OI",
    "OMAB",
    "OMER",
    "ONDS",
    "ONTO",
    "OPY",
    "OR",
    "ORCL",
    "ORI",
    "P",
    "ORLY",
    "OSIS",
    "OVCHY",
    "PAAS",
    "PAC",
    "PAG",
    "PANW",
    "PATK",
    "PCVX",
    "PDEX",
    "PEP",
    "PFE",
    "PFS",
    "PFSI",
    "PGR",
    "PH",
    "PHG",
    "PIPR",
    "PLD",
    "PLPC",
    "PLUS",
    "PLXS",
    "PM",
    "PNFP",
    "PNRG",
    "POWL",
    "PPIH",
    "PPTA",
    "PRI",
    "PRIM",
    "PSIX",
    "PWR",
    "PYPL",
    "QCOM",
    "QQQ",
    "QXO",
    "R",
    "RBA",
    "RBC",
    "RBCAA",
    "RCL",
    "RCMT",
    "RDNT",
    "REAL",
    "REGN",
    "RELX",
    "RF",
    "RGC",
    "RGLD",
    "RGS",
    "RJF",
    "RMBS",
    "RNMBY",
    "ROP",
    "ROST",
    "RTX",
    "RUSHB",
    "RVTY",
    "RXEEY",
    "RY",
    "RYAAY",
    "SAFRY",
    "SAIA",
    "SAIC",
    "SANM",
    "SAR",
    "SBCF",
    "SBGSY",
    "SBH",
    "SBS",
    "SBUX",
    "SCCO",
    "SCHW",
    "SENEA",
    "SGGKY",
    "SGI",
    "SHC",
    "SHOO",
    "SIEGY",
    "SIETY",
    "SII",
    "SIM",
    "SIMO",
    "SKYW",
    "SLF",
    "SMID",
    "SMTOY",
    "SNA",
    "SNDR",
    "SNDX",
    "SNEX",
    "SNFCA",
    "SNPS",
    "SNX",
    "SO",
    "SONY",
    "SPRY",
    "SPXC",
    "SPXCY",
    "SPY",
    "SRCE",
    "SRPT",
    "SSRM",
    "SSUMY",
    "ST",
    "STLD",
    "STN",
    "STRL",
    "STT",
    "STX",
    "SUBCY",
    "SUPN",
    "SVM",
    "SWK",
    "SYF",
    "SYK",
    "T",
    "TALO",
    "TAP",
    "TATT",
    "TAYD",
    "TBBK",
    "TCI",
    "TECH",
    "TECK",
    "TER",
    "TFC",
    "TGB",
    "TGLS",
    "TGS",
    "TGT",
    "THC",
    "THG",
    "TIMB",
    "TIPT",
    "TKO",
    "TLRY",
    "TMO",
    "TMUS",
    "TOELY",
    "TOL",
    "TORXF",
    "TOWN",
    "TPC",
    "TPH",
    "TPR",
    "TRT",
    "TRV",
    "TSEM",
    "TSLA",
    "TSM",
    "TSSI",
    "TT",
    "TTMI",
    "TWO",
    "TX",
    "TXN",
    "TYL",
    "UAL",
    "UAN",
    "UBS",
    "UNH",
    "UNM",
    "UPS",
    "URI",
    "UTHR",
    "UTI",
    "UUUU",
    "V",
    "VECO",
    "VIK",
    "VIRT",
    "VLO",
    "VLVLY",
    "VLY",
    "VMI",
    "VOYA",
    "VRDN",
    "VSXY",
    "VSEC",
    "VZ",
    "WBS",
    "WCC",
    "WDC",
    "WELL",
    "WES",
    "WF",
    "WINA",
    "WLDN",
    "WM",
    "WMB",
    "WMT",
    "WOLF",
    "WOR",
    "WPM",
    "WRB",
    "WRLD",
    "WSBC",
    "WTFC",
    "WTS",
    "WWD",
    "XOM",
    "XPEL",
    "XPO",
    "YETI",
    "YUM",
    "ZETA",
    "ZFSVF",
    "ZIJMY",
    "ZION",
    "ZM",
    "ZTS",
    "ZURVY",
    "ZWS",
    "BABA",
    "BIDU",
    "BILL",
    "BILI",
    "BNTX",
    "CHKP",
    "CRWD",
    "DDOG",
    "DOCU",
    "ESTC",
    "FIVN",
    "FSLY",
    "HUBS",
    "LOGI",
    "MDB",
    "NET",
    "OKTA",
    "PAYC",
    "PINS",
    "PLTR",
    "PTC",
    "RNG",
    "SE",
    "SHOP",
    "SNOW",
    "SSNC",
    "TEAM",
    "TENB",
    "TTD",
    "TWLO",
    "U",
    "VRSN",
    "WDAY",
    "WIX",
    "ZS",
    "ALGN",
    "ALNY",
    "AMN",
    "ARGX",
    "BSX",
    "DXCM",
    "EW",
    "HALO",
    "IDXX",
    "IQV",
    "ISRG",
    "MRNA",
    "NEO",
    "NVAX",
    "NVCR",
    "PACB",
    "RMD",
    "VRTX",
    "ABG",
    "AGCO",
    "BBY",
    "CASY",
    "CHRW",
    "CPRI",
    "DKS",
    "DPZ",
    "DRI",
    "HOG",
    "JACK",
    "KSS",
    "LAD",
    "LCII",
    "M",
    "MAT",
    "NKE",
    "NWL",
    "ORLY",
    "PAG",
    "POOL",
    "PVH",
    "RL",
    "ROST",
    "SBUX",
    "SEE",
    "SHW",
    "SYY",
    "TGT",
    "TJX",
    "TPR",
    "TSCO",
    "TSN",
    "ULTA",
    "VFC",
    "WHR",
    "WYNN",
    "YUM",
    "AME",
    "APC",
    "CAT",
    "CMI",
    "DE",
    "DOV",
    "EOG",
    "ETN",
    "FAST",
    "FTV",
    "GD",
    "GWW",
    "HAL",
    "HON",
    "ITW",
    "JCI",
    "KBR",
    "LMT",
    "MMM",
    "MPC",
    "NOC",
    "ODFL",
    "OXY",
    "PH",
    "ROK",
    "ROP",
    "RSG",
    "SLB",
    "VLO",
    "WAB",
    "WM",
    "XYL",
    "AMP",
    "BLK",
    "CUBE",
    "EXR",
    "FICO",
    "GLPI",
    "GS",
    "IVZ",
    "MS",
    "NTRS",
    "O",
    "PNC",
    "PRU",
    "PSA",
    "SBAC",
    "SCHW",
    "STT",
    "SYF",
    "TFC",
    "TROW",
    "USB",
    "WFC",
    "AA",
    "AAL",
    "AFG",
    "ALB",
    "AMKR",
    "APA",
    "ARW",
    "ASH",
    "ATI",
    "AVT",
    "BC",
    "BWA",
    "CE",
    "CIEN",
    "CINF",
    "CLF",
    "CMC",
    "CNC",
    "CNP",
    "CORT",
    "CRS",
    "CSL",
    "DHI",
    "DY",
    "EME",
    "EMN",
    "ETR",
    "EVR",
    "EXPE",
    "FDS",
    "FLEX",
    "FLS",
    "FMC",
    "FNF",
    "FRT",
    "FTI",
    "G",
    "GGAL",
    "GME",
    "GNTX",
    "GPK",
    "GVA",
    "HP",
    "HURC",
    "ICL",
    "IDA",
    "IDR",
    "IEX",
    "ITT",
    "JBHT",
    "JBLU",
    "KEX",
    "KFY",
    "LBRT",
    "LITE",
    "LNC",
    "LRCX",
    "LSTR",
    "LUV",
    "LVS",
    "MAN",
    "MAS",
    "MCK",
    "MDU",
    "MIDD",
    "MKC",
    "MLM",
    "MMS",
    "MODV",
    "MORN",
    "MTDR",
    "MTX",
    "MUR",
    "NBIX",
    "NBR",
    "NDSN",
    "NE",
    "NEE",
    "NFG",
    "NLY",
    "NMR",
    "NNN",
    "NOV",
    "NRG",
    "NSC",
    "NTAP",
    "NVST",
    "NWS",
    "NXPI",
    "NYT",
    "OC",
    "OGE",
    "OHI",
    "OI",
    "OKE",
    "OLED",
    "OMC",
    "ON",
    "OSK",
    "OTIS",
    "PANW",
    "PAYX",
    "PB",
    "PBI",
    "PCAR",
    "PCG",
    "PEG",
    "PENN",
    "PFG",
    "PG",
    "PHM",
    "PKG",
    "PLD",
    "PLT",
    "PNR",
    "PNW",
    "PPG",
    "PPL",
    "PSX",
    "PTC",
    "PWR",
    "QRVO",
    "REG",
    "RHI",
    "RIG",
    "RJF",
    "ROL",
    "RTX",
    "SLG",
    "SNPS",
    "SO",
    "SPG",
    "SPGI",
    "SRE",
    "STE",
    "STX",
    "STZ",
    "SWK",
    "SWKS",
    "SYK",
    "TDG",
    "TDY",
    "TEL",
    "TER",
    "TFX",
    "TTWO",
    "TXN",
    "TXT",
    "TYL",
    "UA",
    "UDR",
    "UHS",
    "UNP",
    "URI",
    "VNO",
    "VRSK",
    "VTR",
    "VTRS",
    "WAT",
    "WDC",
    "WEC",
    "WRB",
    "WST",
    "WU",
    "WY",
    "XEL",
    "XRAY",
    "XRX",
    "ZBH",
    "ZBRA",
    "ZION",
    "AAPL",
    "ABNB",
    "ACGL",
    "AEP",
    "AES",
    "ALNY",
    "APP",
    "ARM",
    "ASML",
    "AVB",
    "AXON",
    "BBWI",
    "BKNG",
    "BKR",
    "CAG",
    "CAH",
    "CARR",
    "CB",
    "CCEP",
    "CEG",
    "CHD",
    "CMCSA",
    "COST",
    "CPAY",
    "CPRT",
    "DASH",
    "DGX",
    "DLR",
    "DOC",
    "DOW",
    "DTE",
    "DUK",
    "EG",
    "ELV",
    "EPAM",
    "EXC",
    "FER",
    "FICO",
    "FOX",
    "FSLR",
    "GEHC",
    "GEN",
    "GNRC",
    "GOOG",
    "HPE",
    "HPQ",
    "HST",
    "IBM",
    "IDXX",
    "INSM",
    "INVH",
    "IT",
    "J",
    "KDP",
    "KHC",
    "KVUE",
    "LULU",
    "MAA",
    "MET",
    "MO",
    "MOH",
    "MPWR",
    "MSCI",
    "MSI",
    "NVR",
    "NWSA",
    "O",
    "OTIS",
    "PAYC",
    "PCG",
    "PPL",
    "REG",
    "SJM",
    "SOLV",
    "SRE",
    "STZ",
    "TRGP",
    "TRMB",
    "TRV",
    "VICI",
    "VLTO",
    "VMC",
    "WBD",
    "WEC",
    "WST",
    "WTW",
    "XEL"
]
def _compute_start_date(mode: str, incremental_days: int) -> str:
    if mode == "full":
        return START_DATE
    start_dt = datetime.now() - timedelta(days=max(1, int(incremental_days)))
    return start_dt.strftime("%Y-%m-%d")


def _read_existing_coverage_start(output_file: str) -> datetime | None:
    if not os.path.exists(output_file):
        return None
    try:
        old = pd.read_csv(output_file, usecols=["Date"], parse_dates=["Date"])
        if old.empty or "Date" not in old.columns:
            return None
        mn = old["Date"].min()
        if pd.isna(mn):
            return None
        return pd.Timestamp(mn).to_pydatetime()
    except Exception:
        return None


def _should_backfill_full_history(output_file: str, start_date: str) -> bool:
    """
    In incremental mode, backfill full history when the local CSV is missing or does not
    cover the configured start date.
    """
    cov_start = _read_existing_coverage_start(output_file)
    if cov_start is None:
        return True
    try:
        req_start = datetime.strptime(start_date, "%Y-%m-%d")
    except ValueError:
        return False
    # If earliest local bar is after configured start, we are missing history.
    return cov_start.date() > req_start.date()


def _extract_symbol_frame(download_df: pd.DataFrame, ticker: str) -> pd.DataFrame:
    if download_df is None or download_df.empty:
        return pd.DataFrame()
    try:
        if isinstance(download_df.columns, pd.MultiIndex):
            if ticker in download_df.columns.get_level_values(0):
                return download_df[ticker].copy()
            return pd.DataFrame()
        cols = {"Open", "High", "Low", "Close", "Adj Close", "Volume"}
        if len(cols.intersection(set(download_df.columns))) > 0:
            return download_df.copy()
        if ticker in download_df.columns:
            return download_df[ticker].copy()
    except Exception:
        return pd.DataFrame()
    return pd.DataFrame()


def _ensure_db_table(con: duckdb.DuckDBPyConnection, table: str) -> None:
    con.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {table} (
            symbol VARCHAR NOT NULL,
            date DATE NOT NULL,
            open DOUBLE,
            high DOUBLE,
            low DOUBLE,
            close DOUBLE,
            volume DOUBLE,
            source_file VARCHAR,
            loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    con.execute(f"CREATE INDEX IF NOT EXISTS idx_{table}_symbol_date ON {table}(symbol, date)")


def _upsert_symbol_to_db(con: duckdb.DuckDBPyConnection, table: str, symbol: str, df: pd.DataFrame) -> None:
    if df.empty:
        return
    raw = df.reset_index().rename(columns={"index": "Date"}).copy()
    if "Date" not in raw.columns:
        return
    raw["Date"] = pd.to_datetime(raw["Date"]).dt.date
    for col in ("Open", "High", "Low", "Close", "Volume"):
        if col not in raw.columns:
            raw[col] = None
    raw["symbol"] = symbol
    raw["source_file"] = f"{symbol}.csv"
    stage = raw[["symbol", "Date", "Open", "High", "Low", "Close", "Volume", "source_file"]].copy()
    con.register("stage_prices", stage)
    con.execute(
        f"""
        MERGE INTO {table} t
        USING stage_prices s
        ON t.symbol = s.symbol AND t.date = s.Date
        WHEN MATCHED THEN UPDATE SET
            open = s.Open,
            high = s.High,
            low = s.Low,
            close = s.Close,
            volume = s.Volume,
            source_file = s.source_file,
            loaded_at = CURRENT_TIMESTAMP
        WHEN NOT MATCHED THEN INSERT (symbol, date, open, high, low, close, volume, source_file)
            VALUES (s.symbol, s.Date, s.Open, s.High, s.Low, s.Close, s.Volume, s.source_file)
        """
    )
    con.unregister("stage_prices")


def _merge_with_existing_csv(output_file: str, fresh_df: pd.DataFrame) -> pd.DataFrame:
    if os.path.exists(output_file):
        try:
            old = pd.read_csv(output_file, parse_dates=["Date"])
            old = old.set_index("Date").sort_index()
            merged = pd.concat([old, fresh_df], axis=0)
            merged = merged[~merged.index.duplicated(keep="last")].sort_index()
            return merged
        except Exception:
            return fresh_df
    return fresh_df


def main():
    parser = argparse.ArgumentParser(description="Download/update OHLCV CSVs and DuckDB for all configured tickers.")
    parser.add_argument("--mode", choices=["incremental", "full"], default=DEFAULT_MODE)
    parser.add_argument("--incremental-days", type=int, default=DEFAULT_INCREMENTAL_DAYS)
    parser.add_argument("--data-dir", type=str, default=DATA_DIR)
    parser.add_argument("--db-path", type=str, default=DEFAULT_DB_PATH)
    parser.add_argument("--db-table", type=str, default=DEFAULT_DB_TABLE)
    parser.add_argument("--no-db", action="store_true", help="Disable DuckDB upsert for this run.")
    parser.add_argument(
        "--force-history-backfill",
        action="store_true",
        help="One-time: full re-download all symbols from START_DATE (default: auto-detect missing history only).",
    )
    args = parser.parse_args()

    if not os.path.exists(args.data_dir):
        os.makedirs(args.data_dir)

    incremental_start = _compute_start_date("incremental", args.incremental_days)
    full_symbols: list[str] = []
    incremental_symbols: list[str] = []
    for ticker in TICKERS:
        output_file = os.path.join(args.data_dir, f"{ticker}.csv")
        if args.mode == "full" or args.force_history_backfill:
            full_symbols.append(ticker)
            continue
        if ticker in FORCE_FULL_BACKFILL_SYMBOLS and _should_backfill_full_history(output_file, START_DATE):
            full_symbols.append(ticker)
            continue
        if _should_backfill_full_history(output_file, START_DATE):
            full_symbols.append(ticker)
        else:
            incremental_symbols.append(ticker)

    print(f"History start date (START_DATE): {START_DATE}")
    if args.force_history_backfill:
        print(f"[backfill] Force full history for all {len(full_symbols)} symbols.")
    elif full_symbols:
        print(f"[backfill] {len(full_symbols)} symbol(s) missing history before {START_DATE} -> full download.")
    print(
        f"Downloading data for {len(TICKERS)} symbols to {END_DATE} "
        f"(mode={args.mode}, full={len(full_symbols)}, incremental={len(incremental_symbols)})..."
    )
    data_full = pd.DataFrame()
    if full_symbols:
        data_full = yf.download(
            full_symbols,
            start=START_DATE,
            end=END_DATE,
            group_by="ticker",
            threads=True,
            multi_level_index=False,
            auto_adjust=False,
        )
    if incremental_symbols:
        data_inc = yf.download(
            incremental_symbols,
            start=incremental_start,
            end=END_DATE,
            group_by="ticker",
            threads=True,
            multi_level_index=False,
            auto_adjust=False,
        )

    if (not full_symbols or data_full is None or data_full.empty) and (not incremental_symbols or data_inc is None or data_inc.empty):
        print("No data returned from yfinance.")
        return

    use_db = not bool(args.no_db)
    con = None
    if use_db:
        if duckdb is None:
            raise RuntimeError("duckdb package is required for default DB updates. Install: python -m pip install duckdb")
        con = duckdb.connect(args.db_path)
        _ensure_db_table(con, args.db_table)

    sma_periods = [20, 30, 50, 100, 200]
    updated = 0
    skipped = 0

    try:
        for ticker in TICKERS:
            try:
                output_file = os.path.join(args.data_dir, f"{ticker}.csv")
                is_full_download = ticker in full_symbols
                source_df = data_full if is_full_download else data_inc
                df_new = _extract_symbol_frame(source_df, ticker)
                if df_new.empty:
                    skipped += 1
                    continue
                df_new = df_new.dropna(subset=["Open", "High", "Low", "Close"])
                if df_new.empty:
                    skipped += 1
                    continue

                if is_full_download:
                    df_full = df_new.sort_index()
                else:
                    df_full = _merge_with_existing_csv(output_file, df_new.sort_index())

                close = df_full["Close"]
                for period in sma_periods:
                    col = f"SMA{period}"
                    df_full[col] = close.rolling(window=period, min_periods=period).mean().fillna(0)

                df_full.to_csv(output_file, float_format="%.4f")
                if con is not None:
                    _upsert_symbol_to_db(con, args.db_table, ticker, df_new)
                updated += 1
            except Exception as e:
                skipped += 1
                print(f"Skipped {ticker}: {e}")
    finally:
        if con is not None:
            con.close()

    if use_db and _prune_orphan_symbols is not None:
        try:
            pruned = _prune_orphan_symbols(args.db_path, args.data_dir, args.db_table)
            if pruned:
                preview = ", ".join(pruned[:12])
                more = f" (+{len(pruned) - 12} more)" if len(pruned) > 12 else ""
                print(
                    f"Pruned {len(pruned)} orphan symbol(s) from DuckDB "
                    f"(not in TICKERS and/or missing CSV): {preview}{more}"
                )
        except Exception as e:
            print(f"DuckDB prune skipped: {e}")

    print(f"Update Complete. Updated={updated}, Skipped={skipped}, DB={'on' if use_db else 'off'}")

if __name__ == "__main__":
    main()